import '../models.dart';

const String androidCapabilityDependenciesStart =
    '// <mini-program-native-dependencies>';
const String androidCapabilityDependenciesEnd =
    '// </mini-program-native-dependencies>';
const String androidCapabilityGradleGeneratedMarker =
    '// Generated by mini_program_tooling. Do not edit.';

const String androidQrDependencyCapability = 'qr';
const String androidMediaPlaybackDependencyCapability = 'media-playback';

const Map<String, List<String>> _dependencies = <String, List<String>>{
  androidMediaPlaybackDependencyCapability: <String>[
    'androidx.media3:media3-exoplayer:1.5.1',
    'androidx.media3:media3-exoplayer-hls:1.5.1',
    'androidx.media3:media3-ui:1.5.1',
    'androidx.media3:media3-datasource:1.5.1',
    'androidx.media3:media3-database:1.5.1',
  ],
  androidQrDependencyCapability: <String>[
    'androidx.camera:camera-camera2:1.4.2',
    'androidx.camera:camera-lifecycle:1.4.2',
    'androidx.camera:camera-view:1.4.2',
    'com.google.mlkit:barcode-scanning:17.3.0',
  ],
};

class AndroidCapabilityGradleEdit {
  const AndroidCapabilityGradleEdit({
    required this.appGradleSource,
    required this.generatedGradleSource,
  });

  final String appGradleSource;
  final String generatedGradleSource;
}

AndroidCapabilityGradleEdit buildAndroidCapabilityGradleEdit(
  String source, {
  required String? generatedSource,
  required String capability,
  required bool kotlinDsl,
}) {
  if (!_dependencies.containsKey(capability)) {
    throw MiniProgramHostCapabilityException(
      'Unsupported generated Android dependency capability `$capability`.',
    );
  }
  _validateManagedBlock(source);
  if (generatedSource != null &&
      !generatedSource.contains(androidCapabilityGradleGeneratedMarker)) {
    throw const MiniProgramHostCapabilityException(
      'Refusing to overwrite the Android mini-program dependency script '
      'because it is not a recognized tooling-generated file.',
    );
  }
  final newline = source.contains('\r\n') ? '\r\n' : '\n';
  final capabilities = _managedCapabilities(source)
    ..addAll(_legacyCapabilities(source))
    ..addAll(_managedCapabilities(generatedSource ?? ''))
    ..add(capability);
  var base = _removeManagedBlock(source);
  base = _removeLegacyBlock(base, 'mini-program-qr-capability');
  base = _removeLegacyBlock(base, 'mini-program-media-playback-capability');
  base = base.trimRight();
  // Applied Kotlin scripts are analyzed as standalone source files by Android
  // lint. Some AGP/Kotlin combinations cannot associate those scripts with a
  // KaModule and crash release builds. A Groovy script is valid from both
  // Groovy and Kotlin host build files and avoids that lint failure.
  const scriptName = 'mini_program_capabilities.gradle';
  final applyLine = kotlinDsl
      ? 'apply(from = "mini_program/$scriptName")'
      : "apply from: 'mini_program/$scriptName'";
  final appBlock = <String>[
    androidCapabilityDependenciesStart,
    applyLine,
    androidCapabilityDependenciesEnd,
  ].join(newline);
  final generated = _buildGeneratedDependencyScript(
    capabilities,
    appGradleSource: base,
  );
  return AndroidCapabilityGradleEdit(
    appGradleSource: '$base$newline$newline$appBlock$newline',
    generatedGradleSource: generated,
  );
}

String patchAndroidCapabilityDependencies(
  String source, {
  required String capability,
  required bool kotlinDsl,
}) {
  if (!_dependencies.containsKey(capability)) {
    throw MiniProgramHostCapabilityException(
      'Unsupported generated Android dependency capability `$capability`.',
    );
  }
  _validateManagedBlock(source);
  final newline = source.contains('\r\n') ? '\r\n' : '\n';
  final capabilities = _managedCapabilities(source)
    ..addAll(_legacyCapabilities(source))
    ..add(capability);
  var base = _removeManagedBlock(source);
  base = _removeLegacyBlock(base, 'mini-program-qr-capability');
  base = _removeLegacyBlock(base, 'mini-program-media-playback-capability');
  base = base.trimRight();

  final quote = kotlinDsl ? '"' : "'";
  final dependencyLines = <String>[];
  for (final capabilityName in _dependencies.keys.where(
    capabilities.contains,
  )) {
    for (final dependency in _dependencies[capabilityName]!) {
      if (base.contains(dependency)) continue;
      dependencyLines.add(
        kotlinDsl
            ? '    implementation($quote$dependency$quote)'
            : '    implementation $quote$dependency$quote',
      );
    }
  }
  final orderedCapabilities = _dependencies.keys.where(capabilities.contains);
  final block = <String>[
    androidCapabilityDependenciesStart,
    '// capabilities: ${orderedCapabilities.join(', ')}',
    if (dependencyLines.isNotEmpty) ...<String>[
      'dependencies {',
      ...dependencyLines,
      '}',
    ],
    androidCapabilityDependenciesEnd,
  ].join(newline);
  return '$base$newline$newline$block$newline';
}

bool hasManagedAndroidCapabilityDependencies(
  String source,
  String capability,
) => _managedCapabilities(source).contains(capability);

String _buildGeneratedDependencyScript(
  Set<String> capabilities, {
  required String appGradleSource,
}) {
  final dependencyLines = <String>[];
  for (final capabilityName in _dependencies.keys.where(
    capabilities.contains,
  )) {
    for (final dependency in _dependencies[capabilityName]!) {
      if (appGradleSource.contains(dependency)) continue;
      dependencyLines.add('    add "implementation", "$dependency"');
    }
  }
  final orderedCapabilities = _dependencies.keys.where(capabilities.contains);
  return <String>[
    androidCapabilityGradleGeneratedMarker,
    '// capabilities: ${orderedCapabilities.join(', ')}',
    'dependencies {',
    ...dependencyLines,
    '}',
    '',
  ].join('\n');
}

Set<String> _managedCapabilities(String source) {
  final start = source.indexOf(androidCapabilityDependenciesStart);
  final end = source.indexOf(androidCapabilityDependenciesEnd, start + 1);
  final block = start != -1 && end > start
      ? source.substring(start, end)
      : source.contains(androidCapabilityGradleGeneratedMarker)
      ? source
      : '';
  if (block.isEmpty) return <String>{};
  final matches = RegExp(
    r'^// capabilities:\s*(.*)$',
    multiLine: true,
  ).allMatches(block);
  return <String>{
    for (final match in matches)
      ...match
          .group(1)!
          .split(',')
          .map((value) => value.trim())
          .where(_dependencies.containsKey),
  };
}

Set<String> _legacyCapabilities(String source) => <String>{
  if (source.contains('mini-program-qr-capability'))
    androidQrDependencyCapability,
  if (source.contains('mini-program-media-playback-capability'))
    androidMediaPlaybackDependencyCapability,
};

void _validateManagedBlock(String source) {
  final starts = _occurrences(source, androidCapabilityDependenciesStart);
  final ends = _occurrences(source, androidCapabilityDependenciesEnd);
  if (starts > 1 || ends > 1 || starts != ends) {
    throw const MiniProgramHostCapabilityException(
      'The Android app Gradle file contains a malformed generated native '
      'dependency block. Reconcile the block before retrying.',
    );
  }
}

String _removeManagedBlock(String source) => source.replaceFirst(
  RegExp(
    '${RegExp.escape(androidCapabilityDependenciesStart)}'
    r'[\s\S]*?'
    '${RegExp.escape(androidCapabilityDependenciesEnd)}(?:\\r?\\n)?',
  ),
  '',
);

String _removeLegacyBlock(String source, String marker) => source.replaceFirst(
  RegExp(
    '(?:\\r?\\n)?// ${RegExp.escape(marker)}\\s*\\r?\\n'
    r'dependencies\s*\{[\s\S]*?\}\s*',
  ),
  '',
);

int _occurrences(String source, String value) {
  var count = 0;
  var start = 0;
  while (true) {
    final index = source.indexOf(value, start);
    if (index == -1) return count;
    count += 1;
    start = index + value.length;
  }
}
