import '../models.dart';
import 'main_activity_editor.dart';

const String androidNativeSetupGeneratedMarker =
    '// Generated by mini_program_tooling. Do not edit.';

Set<String> readAndroidNativeSetupRegistrations(String? source) {
  if (source == null) return <String>{};
  if (!source.contains(androidNativeSetupGeneratedMarker) ||
      !source.contains('object MiniProgramNativeSetup')) {
    throw const MiniProgramHostCapabilityException(
      'Refusing to overwrite MiniProgramNativeSetup.kt because it is not a '
      'recognized tooling-generated file.',
    );
  }
  return <String>{
    for (final registration in androidCapabilityRegistrations)
      if (source.contains(registration)) registration,
  };
}

String buildAndroidNativeSetupSource({
  required String packageName,
  required String mainActivitySource,
  required String? currentSource,
  required String registration,
}) {
  if (!androidCapabilityRegistrations.contains(registration)) {
    throw MiniProgramHostCapabilityException(
      'Unsupported generated Android registration `$registration`.',
    );
  }
  final registrations = readAndroidNativeSetupRegistrations(currentSource)
    ..addAll(readAndroidMainActivityRegistrations(mainActivitySource))
    ..add(registration);
  return _renderAndroidNativeSetupSource(packageName, registrations);
}

String? removeAndroidNativeSetupRegistration({
  required String source,
  required String registration,
}) {
  final registrations = readAndroidNativeSetupRegistrations(source)
    ..remove(registration);
  if (registrations.isEmpty) return null;
  final packageMatch = RegExp(
    r'^package\s+([A-Za-z_][A-Za-z0-9_.]*)\s*$',
    multiLine: true,
  ).firstMatch(source);
  final packageName = packageMatch?.group(1);
  if (packageName == null) {
    throw const MiniProgramHostCapabilityException(
      'Generated MiniProgramNativeSetup.kt is missing its Kotlin package.',
    );
  }
  return _renderAndroidNativeSetupSource(packageName, registrations);
}

String _renderAndroidNativeSetupSource(
  String packageName,
  Set<String> registrations,
) {
  final lines = <String>[
    'package $packageName',
    '',
    'import io.flutter.embedding.engine.FlutterEngine',
    '',
    androidNativeSetupGeneratedMarker,
    'internal object MiniProgramNativeSetup {',
    '    fun register(flutterEngine: FlutterEngine) {',
    for (final candidate in androidCapabilityRegistrations)
      if (registrations.contains(candidate)) '        $candidate',
    '    }',
    '}',
    '',
  ];
  return lines.join('\n');
}
