import 'dart:convert';

import 'json_values.dart';
import 'models.dart';
import 'records.dart';

Map<String, HostEndpointRecord> parseGeneratedHostEndpoints(
  String source,
  String filePath,
) {
  final match = RegExp(
    r'// BEGIN MINI_PROGRAM_ENDPOINTS_JSON\s*// ([\s\S]*?)\s*// END MINI_PROGRAM_ENDPOINTS_JSON',
  ).firstMatch(source);
  if (match == null) {
    return <String, HostEndpointRecord>{};
  }
  final encodedJson = match.group(1)!.trim();
  final decoded = jsonDecode(encodedJson);
  if (decoded is! Map) {
    throw MiniProgramHostException(
      'Generated endpoint metadata is invalid in $filePath.',
    );
  }
  return decoded.map((key, value) {
    if (value is! Map) {
      throw MiniProgramHostException(
        'Generated endpoint entry "$key" is invalid in $filePath.',
      );
    }
    final apiBaseUri = value['apiBaseUri']?.toString().trim() ?? '';
    if (apiBaseUri.isEmpty) {
      throw MiniProgramHostException(
        'Generated endpoint entry "$key" is incomplete in $filePath.',
      );
    }
    return MapEntry(key.toString(), HostEndpointRecord(apiBaseUri: apiBaseUri));
  });
}

bool isManagedHostEndpointFile(String source) {
  return source.contains('// BEGIN MINI_PROGRAM_ENDPOINTS_JSON') &&
      source.contains('// END MINI_PROGRAM_ENDPOINTS_JSON');
}

String buildHostEndpointFile(
  Map<String, HostEndpointRecord> endpoints,
  Map<String, HostRegistryRecord> registry,
) {
  final sortedEntries = endpoints.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key));
  final jsonMetadata = jsonEncode(<String, Object?>{
    for (final entry in sortedEntries)
      entry.key: <String, Object?>{'apiBaseUri': entry.value.apiBaseUri},
  });
  final buffer = StringBuffer()
    ..writeln('// Generated by `miniprogram host endpoint add`.')
    ..writeln('// Keep endpoint ownership in host config, not button code.')
    ..writeln('// BEGIN MINI_PROGRAM_ENDPOINTS_JSON')
    ..writeln('// $jsonMetadata')
    ..writeln('// END MINI_PROGRAM_ENDPOINTS_JSON')
    ..writeln()
    ..writeln("import 'package:mini_program_sdk/mini_program_sdk.dart';")
    ..writeln()
    ..writeln("import 'mini_program_policy_resolver.dart';")
    ..writeln("import 'mini_program_registry.dart';")
    ..writeln()
    ..writeln('Map<String, MiniProgramEndpoint> buildMiniProgramEndpoints() {')
    ..writeln('  return <String, MiniProgramEndpoint>{');
  for (final entry in sortedEntries) {
    final registryEntry = registry[entry.key];
    final mapKey = registryEntry == null
        ? hostDartString(entry.key)
        : 'MiniPrograms.${registryEntry.constantName}.appId';
    buffer
      ..writeln('    $mapKey: MiniProgramEndpoint.public(')
      ..writeln(
        '      apiBaseUri: Uri.parse(${hostDartString(entry.value.apiBaseUri)}),',
      )
      ..writeln('      cachePolicy: cachePolicyForMiniProgram($mapKey),')
      ..writeln(
        '      liveStatePolicy: liveStatePolicyForMiniProgram($mapKey),',
      )
      ..writeln(
        '      publisherApiPolicy: publisherApiPolicyForMiniProgram($mapKey),',
      )
      ..writeln('      locationPolicy: locationPolicyForMiniProgram($mapKey),')
      ..writeln('      requestTimeout: const Duration(seconds: 20),');
    buffer.writeln('    ),');
  }
  buffer
    ..writeln('  };')
    ..writeln('}')
    ..writeln();
  return buffer.toString();
}
