import 'json_values.dart';
import 'policy_document.dart';

const List<String> hostPolicyCacheBucketOrder = <String>[
  'memory',
  'data',
  'image',
  'state',
  'video',
];

const Set<String> hostMiniProgramRuntimeCacheBuckets = <String>{
  'memory',
  'data',
  'image',
  'state',
};

String buildHostPolicyResolverFile(Map<String, Object?> policies) {
  final apps = hostJsonObjectOrEmpty(policies['apps']);
  final sortedEntries = apps.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key));
  final buffer = StringBuffer()
    ..writeln('// Generated by miniprogram tooling.')
    ..writeln('// Runtime uses accepted host policy only.')
    ..writeln()
    ..writeln(
      "import 'package:mini_program_contracts/mini_program_contracts.dart' "
      'show MiniProgramLocationAccuracy, MiniProgramLocationMode;',
    )
    ..writeln("import 'package:mini_program_sdk/mini_program_sdk.dart';")
    ..writeln()
    ..writeln('MiniProgramCachePolicy cachePolicyForMiniProgram(')
    ..writeln('  String appId,')
    ..writeln(') {')
    ..writeln('  switch (appId) {');
  for (final entry in sortedEntries) {
    final appPolicy = hostJsonObjectOrEmpty(entry.value);
    final accepted = hostJsonObjectOrEmpty(appPolicy['accepted']);
    final cache = hostJsonObjectOrEmpty(accepted['cache']);
    buffer
      ..writeln('    case ${hostDartString(entry.key)}:')
      ..writeln('      return ${_hostCachePolicyExpression(cache)};');
  }
  buffer
    ..writeln('    default:')
    ..writeln('      return const MiniProgramCachePolicy();')
    ..writeln('  }')
    ..writeln('}')
    ..writeln()
    ..writeln('MiniProgramLiveStatePolicy liveStatePolicyForMiniProgram(')
    ..writeln('  String appId,')
    ..writeln(') {')
    ..writeln('  switch (appId) {');
  for (final entry in sortedEntries) {
    final appPolicy = hostJsonObjectOrEmpty(entry.value);
    final accepted = hostJsonObjectOrEmpty(appPolicy['accepted']);
    final liveState = validateHostLiveStatePolicy(
      hostJsonObjectOrEmpty(accepted['liveState']),
    );
    buffer
      ..writeln('    case ${hostDartString(entry.key)}:')
      ..writeln('      return ${_hostLiveStatePolicyExpression(liveState)};');
  }
  buffer
    ..writeln('    default:')
    ..writeln('      return const MiniProgramLiveStatePolicy();')
    ..writeln('  }')
    ..writeln('}')
    ..writeln()
    ..writeln('MiniProgramPublisherApiPolicy publisherApiPolicyForMiniProgram(')
    ..writeln('  String appId,')
    ..writeln(') {')
    ..writeln('  switch (appId) {');
  for (final entry in sortedEntries) {
    final appPolicy = hostJsonObjectOrEmpty(entry.value);
    final accepted = hostJsonObjectOrEmpty(appPolicy['accepted']);
    final publisherApi = accepted['publisherApi'] is Map
        ? validateAcceptedHostPublisherApi(
            hostJsonObjectOrEmpty(accepted['publisherApi']),
          )
        : <String, Object?>{'enabled': false};
    buffer
      ..writeln('    case ${hostDartString(entry.key)}:')
      ..writeln(
        '      return const MiniProgramPublisherApiPolicy('
        'enabled: ${publisherApi['enabled']});',
      );
  }
  buffer
    ..writeln('    default:')
    ..writeln('      return const MiniProgramPublisherApiPolicy();')
    ..writeln('  }')
    ..writeln('}')
    ..writeln()
    ..writeln('MiniProgramLocationPolicy locationPolicyForMiniProgram(')
    ..writeln('  String appId,')
    ..writeln(') {')
    ..writeln('  switch (appId) {');
  for (final entry in sortedEntries) {
    final appPolicy = hostJsonObjectOrEmpty(entry.value);
    final accepted = hostJsonObjectOrEmpty(appPolicy['accepted']);
    final permissions = validateAcceptedHostPermissions(
      hostJsonObjectOrEmpty(accepted['permissions']),
    );
    final location = permissions['location'] is Map
        ? hostJsonObjectOrEmpty(permissions['location'])
        : <String, Object?>{
            'enabled': false,
            'accuracy': 'approximate',
            'mode': 'whenInUse',
          };
    buffer
      ..writeln('    case ${hostDartString(entry.key)}:')
      ..writeln(
        '      return const MiniProgramLocationPolicy('
        'enabled: ${location['enabled'] == true}, '
        'accuracy: MiniProgramLocationAccuracy.approximate, '
        'mode: MiniProgramLocationMode.whenInUse);',
      );
  }
  buffer
    ..writeln('    default:')
    ..writeln('      return const MiniProgramLocationPolicy();')
    ..writeln('  }')
    ..writeln('}')
    ..writeln();
  return buffer.toString();
}

String _hostLiveStatePolicyExpression(Map<String, Object?> liveState) {
  return 'const MiniProgramLiveStatePolicy('
      'maxBytes: ${liveState['maxBytes']}, '
      'maxEntries: ${liveState['maxEntries']}, '
      'maxValueBytes: ${liveState['maxValueBytes']}, '
      'maxDepth: ${liveState['maxDepth']})';
}

String _hostCachePolicyExpression(Map<String, Object?> acceptedCache) {
  if (acceptedCache.isEmpty) {
    return 'const MiniProgramCachePolicy()';
  }
  final args = <String>[];
  final allowedBuckets = <String>[];
  var totalBytes = 0;

  for (final bucket in hostPolicyCacheBucketOrder) {
    final rawBucketPolicy = acceptedCache[bucket];
    if (rawBucketPolicy is! Map) {
      continue;
    }
    final bucketPolicy = hostJsonObjectOrEmpty(rawBucketPolicy);
    final enabled = bucketPolicy['enabled'] is bool
        ? bucketPolicy['enabled'] as bool
        : true;
    if (!enabled) {
      continue;
    }
    final maxBytes = positiveHostInt(bucketPolicy['maxBytes']);
    if (maxBytes != null) {
      totalBytes += maxBytes;
      final maxField = _hostCacheMaxField(bucket);
      if (maxField != null) {
        args.add('$maxField: $maxBytes');
      }
    }
    final ttlDays = positiveHostInt(bucketPolicy['ttlDays']);
    final ttlField = _hostCacheTtlField(bucket);
    if (ttlDays != null && ttlField != null) {
      args.add('$ttlField: Duration(days: $ttlDays)');
    }
    if (hostMiniProgramRuntimeCacheBuckets.contains(bucket)) {
      allowedBuckets.add(bucket);
    }
  }

  if (totalBytes > 0) {
    args.insert(0, 'maxBytes: $totalBytes');
  }
  final allowedExpressions = allowedBuckets
      .map((bucket) => 'MiniProgramCacheBucket.$bucket')
      .join(', ');
  args.add(
    'allowedMiniProgramCacheBuckets: <MiniProgramCacheBucket>{'
    '$allowedExpressions}',
  );
  return 'const MiniProgramCachePolicy(${args.join(', ')})';
}

String? _hostCacheMaxField(String bucket) {
  return switch (bucket) {
    'data' => 'maxDataBytes',
    'image' => 'maxImageBytes',
    'state' => 'maxStateBytes',
    'video' => 'maxVideoBytes',
    _ => null,
  };
}

String? _hostCacheTtlField(String bucket) {
  return switch (bucket) {
    'memory' => 'memoryTtl',
    'data' => 'dataTtl',
    'image' => 'imageTtl',
    'state' => 'stateInactiveTtl',
    'video' => 'videoTtl',
    _ => null,
  };
}
