import 'json_values.dart';
import 'models.dart';
import 'records.dart';

Map<String, HostRegistryRecord> parseGeneratedHostRegistry(
  String source,
  String filePath,
) {
  if (!source.contains('class MiniPrograms') ||
      !source.contains('MiniProgramInfo')) {
    return <String, HostRegistryRecord>{};
  }
  final records = <String, HostRegistryRecord>{};
  final pattern = RegExp(
    r'''static\s+const\s+([A-Za-z_$][A-Za-z0-9_$]*)\s*=\s*MiniProgramInfo\s*\(\s*appId:\s*(['"])(.*?)\2\s*,\s*title:\s*(['"])(.*?)\4\s*,?\s*\)''',
    dotAll: true,
  );
  for (final match in pattern.allMatches(source)) {
    final constantName = match.group(1)!;
    final appId = match.group(3)!.trim();
    final title = match.group(5)!.trim();
    if (appId.isEmpty || title.isEmpty) {
      throw MiniProgramHostException(
        'Generated registry entry "$constantName" is incomplete in '
        '$filePath.',
      );
    }
    records[appId] = HostRegistryRecord(
      appId: appId,
      title: title,
      constantName: constantName,
    );
  }
  return records;
}

bool isManagedHostRegistryFile(String source) {
  return source.contains('// Generated by miniprogram tooling.') &&
      source.contains('class MiniProgramInfo') &&
      source.contains('class MiniPrograms');
}

String buildHostRegistryFile(Map<String, HostRegistryRecord> registry) {
  final sortedEntries = registry.values.toList()
    ..sort((a, b) => a.appId.compareTo(b.appId));
  final buffer = StringBuffer()
    ..writeln('// Generated by miniprogram tooling.')
    ..writeln(
      '// Keep mini-program appId/title pairs in one place when a host app opens',
    )
    ..writeln('// multiple mini-programs.')
    ..writeln()
    ..writeln('class MiniProgramInfo {')
    ..writeln('  const MiniProgramInfo({')
    ..writeln('    required this.appId,')
    ..writeln('    required this.title,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  final String appId;')
    ..writeln('  final String title;')
    ..writeln('}')
    ..writeln()
    ..writeln('class MiniPrograms {')
    ..writeln('  const MiniPrograms._();')
    ..writeln();
  for (final entry in sortedEntries) {
    buffer
      ..writeln('  static const ${entry.constantName} = MiniProgramInfo(')
      ..writeln('    appId: ${hostDartString(entry.appId)},')
      ..writeln('    title: ${hostDartString(entry.title)},')
      ..writeln('  );')
      ..writeln();
  }
  buffer.writeln('  static const values = <MiniProgramInfo>[');
  for (final entry in sortedEntries) {
    buffer.writeln('    ${entry.constantName},');
  }
  buffer
    ..writeln('  ];')
    ..writeln()
    ..writeln('  static const byAppId = <String, MiniProgramInfo>{');
  for (final entry in sortedEntries) {
    buffer.writeln(
      '    ${hostDartString(entry.appId)}: ${entry.constantName},',
    );
  }
  buffer
    ..writeln('  };')
    ..writeln('}')
    ..writeln();
  return buffer.toString();
}

String normalizeHostTitle(String value) {
  final trimmed = value.trim();
  if (trimmed.isEmpty) {
    throw const MiniProgramHostException(
      'Mini-program title must not be blank.',
    );
  }
  return trimmed;
}

HostRegistryRecord newHostRegistryRecord({
  required String appId,
  required String title,
  required Map<String, HostRegistryRecord> existing,
}) {
  return HostRegistryRecord(
    appId: appId,
    title: normalizeHostTitle(title),
    constantName: uniqueHostRegistryFieldName(
      preferred: dartFieldNameFromHostAppId(appId),
      appId: appId,
      existing: existing,
    ),
  );
}

String uniqueHostRegistryFieldName({
  required String preferred,
  required String appId,
  required Map<String, HostRegistryRecord> existing,
}) {
  final used = existing.values
      .where((entry) => entry.appId != appId)
      .map((entry) => entry.constantName)
      .toSet();
  if (!used.contains(preferred)) {
    return preferred;
  }
  var suffix = 2;
  while (used.contains('$preferred$suffix')) {
    suffix += 1;
  }
  return '$preferred$suffix';
}

String dartFieldNameFromHostAppId(String appId) {
  final parts = appId
      .split(RegExp(r'[^A-Za-z0-9]+'))
      .map((part) => part.trim())
      .where((part) => part.isNotEmpty)
      .toList();
  if (parts.isEmpty) {
    return 'miniProgram';
  }
  final first = parts.first.toLowerCase();
  final rest = parts
      .skip(1)
      .map(
        (part) =>
            part.substring(0, 1).toUpperCase() +
            part.substring(1).toLowerCase(),
      );
  final candidate = <String>[first, ...rest].join();
  final normalized = RegExp(r'^[A-Za-z_$]').hasMatch(candidate)
      ? candidate
      : 'miniProgram$candidate';
  return hostDartKeywords.contains(normalized)
      ? '${normalized}MiniProgram'
      : normalized;
}

String titleFromHostAppId(String appId) {
  final words = appId
      .split(RegExp(r'[._-]+'))
      .map((word) => word.trim())
      .where((word) => word.isNotEmpty)
      .map((word) => word.substring(0, 1).toUpperCase() + word.substring(1))
      .toList();
  return words.isEmpty ? appId : words.join(' ');
}

const Set<String> hostDartKeywords = <String>{
  'abstract',
  'as',
  'assert',
  'async',
  'await',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'covariant',
  'default',
  'deferred',
  'do',
  'dynamic',
  'else',
  'enum',
  'export',
  'extends',
  'extension',
  'external',
  'factory',
  'false',
  'final',
  'finally',
  'for',
  'function',
  'get',
  'hide',
  'if',
  'implements',
  'import',
  'in',
  'interface',
  'is',
  'late',
  'library',
  'mixin',
  'new',
  'null',
  'on',
  'operator',
  'part',
  'required',
  'rethrow',
  'return',
  'sealed',
  'set',
  'show',
  'static',
  'super',
  'switch',
  'sync',
  'this',
  'throw',
  'true',
  'try',
  'typedef',
  'var',
  'void',
  'when',
  'with',
  'while',
  'yield',
};
