import 'dart:convert';
import 'dart:collection';
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mini_program_contracts/mini_program_contracts.dart';
import 'package:mini_program_sdk/mini_program_sdk.dart';
import 'package:mini_program_ui/mini_program_ui.dart';

void main() {
  group('MpScreenValidator', () {
    test('accepts JSON generated by mini_program_ui', () {
      const validator = MpScreenValidator();
      validator.validate(_uiGeneratedScreen(), expectedScreenId: 'coupon_home');
    });

    test('accepts author-generated runtime parity JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.column(
              children: <MpNode>[
                Mp.authBuilder(
                  signedOut: Mp.primaryButton(
                    label: 'Sign in',
                    action: Mp.auth.showEmailAuth(),
                  ),
                  signedIn: Mp.secondaryButton(
                    label: 'Sign out',
                    action: Mp.auth.signOut(),
                  ),
                ),
                Mp.backendBuilder(
                  requestId: 'home',
                  endpoint: 'home/bootstrap',
                  child: Mp.text('{{backend.home.data.title}}'),
                ),
                Mp.pagedBackendBuilder(
                  requestId: 'coupons',
                  endpoint: 'coupons/page',
                  itemTemplate: Mp.text('{{item.title}}'),
                  loadMore: Mp.secondaryButton(
                    label: 'Load more',
                    action: Mp.backend.loadMore(requestId: 'coupons'),
                  ),
                ),
                Mp.primaryButton(
                  label: 'Details',
                  action: Mp.navigation.openScreen('coupon_details'),
                ),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated form JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.form(
              children: <MpNode>[
                Mp.textInput(
                  name: 'full_name',
                  label: 'Full name',
                  required: true,
                  minLength: 2,
                ),
                Mp.textArea(name: 'essay', label: 'Essay', maxLength: 500),
                Mp.dropdown(
                  name: 'program',
                  label: 'Program',
                  options: const <MpOption>[
                    MpOption(value: 'stem', label: 'STEM'),
                    MpOption(value: 'arts', label: 'Arts'),
                  ],
                ),
                Mp.radioGroup(
                  name: 'level',
                  label: 'Level',
                  options: const <MpOption>[
                    MpOption(value: 'undergraduate', label: 'Undergraduate'),
                    MpOption(value: 'graduate', label: 'Graduate'),
                  ],
                  required: true,
                ),
                Mp.checkbox(
                  name: 'terms',
                  label: 'I confirm',
                  requiredTrue: true,
                ),
                Mp.formSubmit(
                  label: 'Submit',
                  endpoint: 'applications/submit',
                  onSuccess: Mp.toast(message: 'Submitted', durationMs: 1),
                  onError: Mp.dialog(message: 'Failed'),
                ),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('rejects malformed Mp screen JSON', () {
      final cases = <String, Map<String, dynamic>>{
        'bad schema': _screenWith((json) {
          json['schemaVersion'] = 2;
        }),
        'screen mismatch': _screenWith((json) {
          json['screenId'] = 'other_home';
        }),
        'unsupported node': _screenWith((json) {
          (json['root'] as Map<String, dynamic>)['type'] = 'video';
        }),
        'malformed props': _screenWith((json) {
          ((json['root'] as Map<String, dynamic>)['children'] as List)
                  .cast<Map<String, dynamic>>()
                  .last['props'] =
              'bad';
        }),
        'invalid action': _screenWith((json) {
          final button =
              ((json['root'] as Map<String, dynamic>)['children'] as List)
                  .cast<Map<String, dynamic>>()
                  .last;
          ((button['props'] as Map<String, dynamic>)['action']
                  as Map<String, dynamic>)['type'] =
              'host.run';
        }),
        'unsafe image url': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'image',
            'props': <String, dynamic>{'src': 'http://example.com/a.png'},
            'children': <Object?>[],
          };
        }),
        'too many children': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'column',
            'props': <String, dynamic>{},
            'children': List<Object?>.generate(
              MpScreenValidator.maxDirectChildren + 1,
              (index) => <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Item $index'},
                'children': <Object?>[],
              },
            ),
          };
        }),
        'unsafe binding path': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': '{{auth.idToken}}'},
            'children': <Object?>[],
          };
        }),
        'unsupported binding root': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': '{{secrets.value}}'},
            'children': <Object?>[],
          };
        }),
        'missing paged item template': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'pagedBackendBuilder',
            'props': <String, dynamic>{
              'requestId': 'coupons',
              'endpoint': 'coupons/page',
            },
            'children': <Object?>[],
          };
        }),
        'empty form': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'form',
            'props': <String, dynamic>{'id': 'application'},
            'children': <Object?>[],
          };
        }),
        'invalid form field name': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'form',
            'props': <String, dynamic>{'id': 'application'},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'textInput',
                'props': <String, dynamic>{
                  'name': 'FullName',
                  'label': 'Full name',
                },
                'children': <Object?>[],
              },
            ],
          };
        }),
        'dropdown initial value mismatch': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'dropdown',
            'props': <String, dynamic>{
              'name': 'program',
              'label': 'Program',
              'initialValue': 'missing',
              'options': <Object?>[
                <String, dynamic>{'value': 'stem', 'label': 'STEM'},
              ],
            },
            'children': <Object?>[],
          };
        }),
        'invalid ui action': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'primaryButton',
            'props': <String, dynamic>{
              'label': 'Save',
              'action': <String, dynamic>{
                'type': 'ui.toast',
                'props': <String, dynamic>{'message': ''},
              },
            },
            'children': <Object?>[],
          };
        }),
      };

      for (final entry in cases.entries) {
        expect(
          () => const MpScreenValidator().validate(
            entry.value,
            expectedScreenId: 'coupon_home',
          ),
          throwsA(isA<MiniProgramRenderException>()),
          reason: entry.key,
        );
      }
    });
  });

  group('MpScreenRenderer', () {
    testWidgets('renders basic Mp nodes with Flutter widgets', (tester) async {
      await tester.pumpWidget(
        MaterialApp(
          home: Builder(
            builder: (context) {
              return const MpScreenRenderer().render(
                MiniProgramRenderRequest(
                  context: context,
                  manifest: _mpManifest,
                  screenId: 'coupon_home',
                  screenJson: _fullBasicScreen,
                  logger: DebugPrintSdkLogger(),
                ),
              );
            },
          ),
        ),
      );

      expect(find.text('Publisher account'), findsOneWidget);
      expect(find.text('Sign in to continue'), findsOneWidget);
      expect(find.text('Inside card'), findsOneWidget);
      expect(find.text('Sign in'), findsOneWidget);
      expect(find.text('Cancel'), findsOneWidget);
      expect(find.byType(Image), findsOneWidget);
    });

    testWidgets('auth button opens the SDK email auth sheet without tokens', (
      tester,
    ) async {
      final controller = MiniProgramAuthController(
        store: InMemoryMiniProgramAuthStore(),
        clock: () => DateTime.utc(2026, 6, 3, 12),
      );
      final connector = _AuthConnector();
      final backendStore = MiniProgramBackendStore();

      await tester.pumpWidget(
        MaterialApp(
          home: MiniProgramSdkScope(
            miniProgramId: 'coupon',
            hostBridge: _NoopHostBridge(),
            capabilityRegistry: CapabilityRegistry(const <CapabilityId>[
              CapabilityIds.auth,
            ]),
            backendConnector: connector,
            authController: controller,
            backendStore: backendStore,
            featureFlagEvaluator: const AllowAllFeatureFlagEvaluator(),
            logger: const DebugPrintSdkLogger(),
            openMiniProgramScreen: (_, _) async => _ok('openMiniProgramScreen'),
            resetMiniProgramStack: (_, _) async => _ok('resetMiniProgramStack'),
            replaceMiniProgramScreen: (_, _) async =>
                _ok('replaceMiniProgramScreen'),
            popMiniProgramScreen: (_, _) async => _ok('popMiniProgramScreen'),
            popToMiniProgramRoot: (_, _) async => _ok('popToMiniProgramRoot'),
            popToMiniProgramScreen: (_, _) async =>
                _ok('popToMiniProgramScreen'),
            child: Builder(
              builder: (context) {
                return const MpScreenRenderer().render(
                  MiniProgramRenderRequest(
                    context: context,
                    manifest: _mpManifest,
                    screenId: 'coupon_home',
                    screenJson: _uiGeneratedScreenConst,
                    logger: DebugPrintSdkLogger(),
                  ),
                );
              },
            ),
          ),
        ),
      );

      await tester.tap(find.text('Sign in'));
      await tester.pumpAndSettle();

      expect(find.text('Email'), findsOneWidget);
      expect(find.text('Password'), findsOneWidget);
      expect(find.textContaining('id-token'), findsNothing);
      expect(find.textContaining('refresh-token'), findsNothing);

      backendStore.dispose();
    });

    testWidgets('authBuilder renders auth state and sign-out action', (
      tester,
    ) async {
      final store = InMemoryMiniProgramAuthStore();
      await store.write('coupon', _session());
      final controller = MiniProgramAuthController(
        store: store,
        clock: _fixedNow,
      );
      await controller.restore(miniProgramId: 'coupon', connector: null);

      final backendStore = MiniProgramBackendStore();
      await tester.pumpWidget(
        _scopedApp(
          backendStore: backendStore,
          authController: controller,
          backendConnector: _AuthConnector(),
          screenJson: _authBuilderScreen,
        ),
      );
      await tester.pump();

      expect(find.text('Signed in as user@example.com'), findsOneWidget);
      expect(find.textContaining('id-token'), findsNothing);

      await tester.tap(find.text('Sign out'));
      await tester.pumpAndSettle();

      expect(controller.snapshot('coupon').signedOut, isTrue);
      expect(find.text('Signed out'), findsOneWidget);

      backendStore.dispose();
    });

    testWidgets('backendBuilder queries data with auth bearer bindings', (
      tester,
    ) async {
      final authStore = InMemoryMiniProgramAuthStore();
      await authStore.write('coupon', _session());
      final controller = MiniProgramAuthController(
        store: authStore,
        clock: _fixedNow,
      );
      await controller.restore(miniProgramId: 'coupon', connector: null);
      final connector = _RecordingBackendConnector(
        responses: <MiniProgramBackendResult>[
          MiniProgramBackendResult.success(
            endpoint: 'home/bootstrap',
            method: 'GET',
            data: const <String, dynamic>{'title': 'Backend title'},
          ),
        ],
      );
      final backendStore = MiniProgramBackendStore();

      await tester.pumpWidget(
        _scopedApp(
          backendStore: backendStore,
          authController: controller,
          backendConnector: connector,
          screenJson: _backendBuilderScreen,
        ),
      );
      await tester.pump();
      await tester.pumpAndSettle();

      expect(find.text('Backend title'), findsOneWidget);
      expect(connector.calls.single.endpoint, 'home/bootstrap');
      expect(
        connector.calls.single.headers['authorization'],
        'Bearer id-token',
      );

      backendStore.dispose();
    });

    testWidgets('pagedBackendBuilder appends items through load more', (
      tester,
    ) async {
      final connector = _RecordingBackendConnector(
        responses: <MiniProgramBackendResult>[
          MiniProgramBackendResult.success(
            endpoint: 'coupons/page?limit=1',
            method: 'GET',
            data: const <String, dynamic>{
              'items': [
                <String, dynamic>{'title': 'Coupon 1'},
              ],
              'nextCursor': 'coupon-1',
              'hasMore': true,
            },
          ),
          MiniProgramBackendResult.success(
            endpoint: 'coupons/page?limit=1&cursor=coupon-1',
            method: 'GET',
            data: const <String, dynamic>{
              'items': [
                <String, dynamic>{'title': 'Coupon 2'},
              ],
              'hasMore': false,
            },
          ),
        ],
      );
      final backendStore = MiniProgramBackendStore();

      await tester.pumpWidget(
        _scopedApp(
          backendStore: backendStore,
          backendConnector: connector,
          screenJson: _pagedBuilderScreen,
        ),
      );
      await tester.pump();
      await tester.pumpAndSettle();

      expect(find.text('Coupon 1'), findsOneWidget);
      expect(find.text('Load more'), findsOneWidget);

      await tester.tap(find.text('Load more'));
      await tester.pumpAndSettle();

      expect(find.text('Coupon 1'), findsOneWidget);
      expect(find.text('Coupon 2'), findsOneWidget);
      expect(find.text('No more coupons'), findsOneWidget);
      expect(connector.calls, hasLength(2));
      expect(
        connector.calls.last.endpoint,
        'coupons/page?limit=1&cursor=coupon-1',
      );

      backendStore.dispose();
    });

    testWidgets('pagedBackendBuilder keeps items on load-more failure', (
      tester,
    ) async {
      final secondPage = Completer<MiniProgramBackendResult>();
      final connector = _FutureBackendConnector(
        responses: <FutureOr<MiniProgramBackendResult>>[
          MiniProgramBackendResult.success(
            endpoint: 'coupons/page?limit=1',
            method: 'GET',
            data: const <String, dynamic>{
              'items': [
                <String, dynamic>{'title': 'Coupon 1'},
              ],
              'nextCursor': 'coupon-1',
              'hasMore': true,
            },
          ),
          secondPage.future,
        ],
      );
      final backendStore = MiniProgramBackendStore();

      await tester.pumpWidget(
        _scopedApp(
          backendStore: backendStore,
          backendConnector: connector,
          screenJson: _pagedBuilderScreen,
        ),
      );
      await tester.pumpAndSettle();
      await tester.tap(find.text('Load more'));
      await tester.pump();

      expect(find.text('Coupon 1'), findsOneWidget);
      expect(find.text('Loading more coupons'), findsOneWidget);

      secondPage.complete(
        MiniProgramBackendResult.failed(
          endpoint: 'coupons/page?limit=1&cursor=coupon-1',
          method: 'GET',
          message: 'Load failed',
          errorCode: 'load_failed',
        ),
      );
      await tester.pumpAndSettle();

      expect(find.text('Coupon 1'), findsOneWidget);
      expect(find.text('Load failed'), findsOneWidget);

      backendStore.dispose();
    });

    testWidgets('navigation actions call existing mini-program handlers', (
      tester,
    ) async {
      final backendStore = MiniProgramBackendStore();
      String? openedScreenId;

      await tester.pumpWidget(
        _scopedApp(
          backendStore: backendStore,
          screenJson: _navigationScreen,
          openMiniProgramScreen: (payload, _) async {
            openedScreenId = payload.screenId;
            return _ok(ActionNames.openMiniProgramScreen);
          },
        ),
      );

      await tester.tap(find.text('Open details'));
      await tester.pump();

      expect(openedScreenId, 'coupon_details');

      backendStore.dispose();
    });

    testWidgets('form controls validate and submit through backend connector', (
      tester,
    ) async {
      final connector = _RecordingBackendConnector(
        responses: <MiniProgramBackendResult>[
          MiniProgramBackendResult.success(
            endpoint: 'applications/submit',
            method: 'POST',
            data: const <String, dynamic>{'ok': true},
          ),
        ],
      );
      final backendStore = MiniProgramBackendStore();

      await tester.pumpWidget(
        _scopedApp(
          backendStore: backendStore,
          backendConnector: connector,
          screenJson: _formScreen,
        ),
      );

      await tester.tap(find.text('Submit application'));
      await tester.pump();

      expect(connector.calls, isEmpty);
      expect(find.text('Check the highlighted fields.'), findsOneWidget);
      expect(find.text('This field is required.'), findsWidgets);

      await tester.enterText(find.byType(EditableText).at(0), 'Mehedi Hasan');
      await tester.enterText(
        find.byType(EditableText).at(1),
        'Scholarship essay',
      );
      await tester.tap(find.text('Choose a program'));
      await tester.pumpAndSettle();
      await tester.tap(find.text('STEM'));
      await tester.pumpAndSettle();
      await tester.tap(find.text('Undergraduate'));
      await tester.tap(find.text('I confirm this application is accurate'));
      await tester.pump();
      await tester.tap(find.text('Submit application'));
      await tester.pump();
      await tester.pump();

      expect(connector.calls, hasLength(1));
      expect(connector.calls.single.endpoint, 'applications/submit');
      expect(connector.calls.single.method, 'POST');
      expect(connector.calls.single.body, <String, dynamic>{
        'full_name': 'Mehedi Hasan',
        'essay': 'Scholarship essay',
        'program': 'stem',
        'level': 'undergraduate',
        'terms': true,
      });
      expect(find.text('Submitted'), findsOneWidget);
      await tester.pump(const Duration(milliseconds: 1));
      await tester.pump();

      backendStore.dispose();
    });

    testWidgets('toast and dialog actions render SDK-owned feedback', (
      tester,
    ) async {
      final backendStore = MiniProgramBackendStore();

      await tester.pumpWidget(
        _scopedApp(backendStore: backendStore, screenJson: _feedbackScreen),
      );

      await tester.tap(find.text('Show toast'));
      await tester.pump();
      expect(find.text('Saved'), findsOneWidget);
      await tester.pump(const Duration(milliseconds: 1));
      await tester.pump();

      await tester.tap(find.text('Show dialog'));
      await tester.pumpAndSettle();
      expect(find.text('Confirm'), findsOneWidget);
      expect(find.text('Continue?'), findsOneWidget);

      await tester.tap(find.text('OK'));
      await tester.pumpAndSettle();
      expect(find.text('Continue?'), findsNothing);

      backendStore.dispose();
    });
  });
}

const MiniProgramManifest _mpManifest = MiniProgramManifest(
  id: 'coupon',
  version: '1.0.0',
  entry: 'coupon_home',
  contractVersion: '1.0.0',
  sdkVersionRange: SdkVersionRange(value: '>=1.0.0 <2.0.0'),
  requiredCapabilities: <CapabilityId>[CapabilityIds.auth],
  screenFormat: MiniProgramScreenFormats.mp,
  screenSchemaVersion: 1,
);

Map<String, dynamic> _uiGeneratedScreen() {
  final miniProgram = MpProgram(
    screens: <String, MpScreenBuilder>{
      'coupon_home': () => Mp.column(
        children: <MpNode>[
          Mp.heading('Publisher account'),
          Mp.text('Sign in to continue'),
          Mp.primaryButton(label: 'Sign in', action: Mp.auth.showEmailAuth()),
        ],
      ),
    },
  );
  return _jsonMap(miniProgram.buildScreensJson()['coupon_home']!);
}

Map<String, dynamic> _screenWith(void Function(Map<String, dynamic>) mutate) {
  final json = _uiGeneratedScreen();
  mutate(json);
  return json;
}

Map<String, dynamic> _jsonMap(Map<String, Object?> json) {
  return Map<String, dynamic>.from(jsonDecode(jsonEncode(json)) as Map);
}

const Map<String, dynamic> _uiGeneratedScreenConst = <String, dynamic>{
  'schemaVersion': 1,
  'screenId': 'coupon_home',
  'root': <String, dynamic>{
    'type': 'column',
    'props': <String, dynamic>{},
    'children': <Object?>[
      <String, dynamic>{
        'type': 'primaryButton',
        'props': <String, dynamic>{
          'label': 'Sign in',
          'action': <String, dynamic>{
            'type': 'auth.showEmailAuth',
            'props': <String, dynamic>{},
          },
        },
        'children': <Object?>[],
      },
    ],
  },
};

const Map<String, dynamic> _authBuilderScreen = <String, dynamic>{
  'schemaVersion': 1,
  'screenId': 'coupon_home',
  'root': <String, dynamic>{
    'type': 'authBuilder',
    'props': <String, dynamic>{
      'signedOut': <String, dynamic>{
        'type': 'text',
        'props': <String, dynamic>{'data': 'Signed out'},
        'children': <Object?>[],
      },
      'signedIn': <String, dynamic>{
        'type': 'column',
        'props': <String, dynamic>{},
        'children': <Object?>[
          <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{
              'data': 'Signed in as {{auth.user.email}}',
            },
            'children': <Object?>[],
          },
          <String, dynamic>{
            'type': 'secondaryButton',
            'props': <String, dynamic>{
              'label': 'Sign out',
              'action': <String, dynamic>{
                'type': 'auth.signOut',
                'props': <String, dynamic>{},
              },
            },
            'children': <Object?>[],
          },
        ],
      },
    },
    'children': <Object?>[],
  },
};

const Map<String, dynamic> _backendBuilderScreen = <String, dynamic>{
  'schemaVersion': 1,
  'screenId': 'coupon_home',
  'root': <String, dynamic>{
    'type': 'backendBuilder',
    'props': <String, dynamic>{
      'requestId': 'home',
      'endpoint': 'home/bootstrap',
      'loading': <String, dynamic>{
        'type': 'text',
        'props': <String, dynamic>{'data': 'Loading backend'},
        'children': <Object?>[],
      },
      'child': <String, dynamic>{
        'type': 'text',
        'props': <String, dynamic>{'data': '{{backend.home.data.title}}'},
        'children': <Object?>[],
      },
    },
    'children': <Object?>[],
  },
};

const Map<String, dynamic> _pagedBuilderScreen = <String, dynamic>{
  'schemaVersion': 1,
  'screenId': 'coupon_home',
  'root': <String, dynamic>{
    'type': 'pagedBackendBuilder',
    'props': <String, dynamic>{
      'requestId': 'coupons',
      'endpoint': 'coupons/page',
      'limit': 1,
      'loading': <String, dynamic>{
        'type': 'text',
        'props': <String, dynamic>{'data': 'Loading coupons'},
        'children': <Object?>[],
      },
      'itemTemplate': <String, dynamic>{
        'type': 'text',
        'props': <String, dynamic>{'data': '{{item.title}}'},
        'children': <Object?>[],
      },
      'loadingMore': <String, dynamic>{
        'type': 'text',
        'props': <String, dynamic>{'data': 'Loading more coupons'},
        'children': <Object?>[],
      },
      'error': <String, dynamic>{
        'type': 'text',
        'props': <String, dynamic>{'data': '{{backend.coupons.message}}'},
        'children': <Object?>[],
      },
      'loadMore': <String, dynamic>{
        'type': 'secondaryButton',
        'props': <String, dynamic>{
          'label': 'Load more',
          'action': <String, dynamic>{
            'type': 'backend.loadMore',
            'props': <String, dynamic>{'requestId': 'coupons'},
          },
        },
        'children': <Object?>[],
      },
      'end': <String, dynamic>{
        'type': 'text',
        'props': <String, dynamic>{'data': 'No more coupons'},
        'children': <Object?>[],
      },
    },
    'children': <Object?>[],
  },
};

const Map<String, dynamic> _navigationScreen = <String, dynamic>{
  'schemaVersion': 1,
  'screenId': 'coupon_home',
  'root': <String, dynamic>{
    'type': 'primaryButton',
    'props': <String, dynamic>{
      'label': 'Open details',
      'action': <String, dynamic>{
        'type': 'navigation.openScreen',
        'props': <String, dynamic>{'screenId': 'coupon_details'},
      },
    },
    'children': <Object?>[],
  },
};

const Map<String, dynamic> _formScreen = <String, dynamic>{
  'schemaVersion': 1,
  'screenId': 'coupon_home',
  'root': <String, dynamic>{
    'type': 'form',
    'props': <String, dynamic>{'id': 'application'},
    'children': <Object?>[
      <String, dynamic>{
        'type': 'textInput',
        'props': <String, dynamic>{
          'name': 'full_name',
          'label': 'Full name',
          'hint': 'Use your legal name',
          'required': true,
          'minLength': 2,
          'keyboardType': 'text',
        },
        'children': <Object?>[],
      },
      <String, dynamic>{
        'type': 'textArea',
        'props': <String, dynamic>{
          'name': 'essay',
          'label': 'Essay',
          'maxLength': 500,
          'minLines': 3,
          'maxLines': 6,
        },
        'children': <Object?>[],
      },
      <String, dynamic>{
        'type': 'dropdown',
        'props': <String, dynamic>{
          'name': 'program',
          'label': 'Program',
          'hint': 'Choose a program',
          'required': true,
          'options': <Object?>[
            <String, dynamic>{'value': 'stem', 'label': 'STEM'},
            <String, dynamic>{'value': 'arts', 'label': 'Arts'},
          ],
        },
        'children': <Object?>[],
      },
      <String, dynamic>{
        'type': 'radioGroup',
        'props': <String, dynamic>{
          'name': 'level',
          'label': 'Level',
          'required': true,
          'options': <Object?>[
            <String, dynamic>{
              'value': 'undergraduate',
              'label': 'Undergraduate',
            },
            <String, dynamic>{'value': 'graduate', 'label': 'Graduate'},
          ],
        },
        'children': <Object?>[],
      },
      <String, dynamic>{
        'type': 'checkbox',
        'props': <String, dynamic>{
          'name': 'terms',
          'label': 'I confirm this application is accurate',
          'requiredTrue': true,
        },
        'children': <Object?>[],
      },
      <String, dynamic>{
        'type': 'formSubmit',
        'props': <String, dynamic>{
          'label': 'Submit application',
          'endpoint': 'applications/submit',
          'method': 'POST',
          'onSuccess': <String, dynamic>{
            'type': 'ui.toast',
            'props': <String, dynamic>{'message': 'Submitted', 'durationMs': 1},
          },
        },
        'children': <Object?>[],
      },
    ],
  },
};

const Map<String, dynamic> _feedbackScreen = <String, dynamic>{
  'schemaVersion': 1,
  'screenId': 'coupon_home',
  'root': <String, dynamic>{
    'type': 'column',
    'props': <String, dynamic>{},
    'children': <Object?>[
      <String, dynamic>{
        'type': 'primaryButton',
        'props': <String, dynamic>{
          'label': 'Show toast',
          'action': <String, dynamic>{
            'type': 'ui.toast',
            'props': <String, dynamic>{'message': 'Saved', 'durationMs': 1},
          },
        },
        'children': <Object?>[],
      },
      <String, dynamic>{
        'type': 'secondaryButton',
        'props': <String, dynamic>{
          'label': 'Show dialog',
          'action': <String, dynamic>{
            'type': 'ui.dialog',
            'props': <String, dynamic>{
              'title': 'Confirm',
              'message': 'Continue?',
            },
          },
        },
        'children': <Object?>[],
      },
    ],
  },
};

const Map<String, dynamic> _fullBasicScreen = <String, dynamic>{
  'schemaVersion': 1,
  'screenId': 'coupon_home',
  'root': <String, dynamic>{
    'type': 'column',
    'props': <String, dynamic>{},
    'children': <Object?>[
      <String, dynamic>{
        'type': 'heading',
        'props': <String, dynamic>{'data': 'Publisher account'},
        'children': <Object?>[],
      },
      <String, dynamic>{
        'type': 'text',
        'props': <String, dynamic>{'data': 'Sign in to continue'},
        'children': <Object?>[],
      },
      <String, dynamic>{
        'type': 'row',
        'props': <String, dynamic>{},
        'children': <Object?>[
          <String, dynamic>{
            'type': 'sizedBox',
            'props': <String, dynamic>{'width': 8, 'height': 8},
            'children': <Object?>[],
          },
          <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Inline'},
            'children': <Object?>[],
          },
        ],
      },
      <String, dynamic>{
        'type': 'image',
        'props': <String, dynamic>{
          'src': 'https://example.com/coupon.png',
          'alt': 'Coupon image',
        },
        'children': <Object?>[],
      },
      <String, dynamic>{
        'type': 'card',
        'props': <String, dynamic>{},
        'children': <Object?>[
          <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Inside card'},
            'children': <Object?>[],
          },
        ],
      },
      <String, dynamic>{
        'type': 'primaryButton',
        'props': <String, dynamic>{
          'label': 'Sign in',
          'action': <String, dynamic>{
            'type': 'auth.showEmailAuth',
            'props': <String, dynamic>{},
          },
        },
        'children': <Object?>[],
      },
      <String, dynamic>{
        'type': 'secondaryButton',
        'props': <String, dynamic>{
          'label': 'Cancel',
          'action': <String, dynamic>{
            'type': 'auth.showEmailAuth',
            'props': <String, dynamic>{},
          },
        },
        'children': <Object?>[],
      },
    ],
  },
};

HostActionResult _ok(String actionName) {
  return HostActionResult.success(actionName: actionName);
}

DateTime _fixedNow() => DateTime.utc(2026, 6, 3, 12);

MiniProgramAuthSession _session() {
  return MiniProgramAuthSession(
    miniProgramId: 'coupon',
    user: const MiniProgramAuthUser(uid: 'user-1', email: 'user@example.com'),
    idToken: 'id-token',
    refreshToken: 'refresh-token',
    expiresAtUtc: _fixedNow().add(const Duration(hours: 1)),
  );
}

Widget _scopedApp({
  required MiniProgramBackendStore backendStore,
  required Map<String, dynamic> screenJson,
  MiniProgramBackendConnector? backendConnector,
  MiniProgramAuthController? authController,
  MiniProgramOpenScreenHandler? openMiniProgramScreen,
}) {
  return MaterialApp(
    home: MiniProgramSdkScope(
      miniProgramId: 'coupon',
      hostBridge: _NoopHostBridge(),
      capabilityRegistry: CapabilityRegistry(const <CapabilityId>[
        CapabilityIds.auth,
      ]),
      backendConnector: backendConnector,
      authController: authController,
      backendStore: backendStore,
      featureFlagEvaluator: const AllowAllFeatureFlagEvaluator(),
      logger: const DebugPrintSdkLogger(),
      openMiniProgramScreen:
          openMiniProgramScreen ?? (_, _) async => _ok('openMiniProgramScreen'),
      resetMiniProgramStack: (_, _) async => _ok('resetMiniProgramStack'),
      replaceMiniProgramScreen: (_, _) async => _ok('replaceMiniProgramScreen'),
      popMiniProgramScreen: (_, _) async => _ok('popMiniProgramScreen'),
      popToMiniProgramRoot: (_, _) async => _ok('popToMiniProgramRoot'),
      popToMiniProgramScreen: (_, _) async => _ok('popToMiniProgramScreen'),
      child: Builder(
        builder: (context) {
          return const MpScreenRenderer().render(
            MiniProgramRenderRequest(
              context: context,
              manifest: _mpManifest,
              screenId: 'coupon_home',
              screenJson: screenJson,
              logger: DebugPrintSdkLogger(),
            ),
          );
        },
      ),
    ),
  );
}

class _AuthConnector implements MiniProgramBackendConnector {
  @override
  Future<MiniProgramBackendResult> call(
    MiniProgramBackendRequest request,
  ) async {
    return MiniProgramBackendResult.success(
      endpoint: request.endpoint,
      method: request.method,
      data: const <String, dynamic>{
        'authenticated': true,
        'user': <String, dynamic>{'uid': 'user-1', 'email': 'user@example.com'},
        'idToken': 'id-token',
        'refreshToken': 'refresh-token',
        'expiresIn': 3600,
      },
    );
  }
}

class _RecordingBackendConnector implements MiniProgramBackendConnector {
  _RecordingBackendConnector({
    required List<MiniProgramBackendResult> responses,
  }) : _responses = Queue<MiniProgramBackendResult>.of(responses);

  final Queue<MiniProgramBackendResult> _responses;
  final List<MiniProgramBackendRequest> calls = <MiniProgramBackendRequest>[];

  @override
  Future<MiniProgramBackendResult> call(
    MiniProgramBackendRequest request,
  ) async {
    calls.add(request);
    return _responses.removeFirst();
  }
}

class _FutureBackendConnector implements MiniProgramBackendConnector {
  _FutureBackendConnector({
    required List<FutureOr<MiniProgramBackendResult>> responses,
  }) : _responses = Queue<FutureOr<MiniProgramBackendResult>>.of(responses);

  final Queue<FutureOr<MiniProgramBackendResult>> _responses;
  final List<MiniProgramBackendRequest> calls = <MiniProgramBackendRequest>[];

  @override
  Future<MiniProgramBackendResult> call(
    MiniProgramBackendRequest request,
  ) async {
    calls.add(request);
    return _responses.removeFirst();
  }
}

class _NoopHostBridge implements HostBridge {
  @override
  Future<HostActionResult> callSecureApi(
    CallSecureApiActionPayload payload,
  ) async {
    return _ok(ActionNames.callSecureApi);
  }

  @override
  Future<HostActionResult> openNativeScreen(
    OpenNativeScreenActionPayload payload,
  ) async {
    return _ok(ActionNames.openNativeScreen);
  }

  @override
  Future<HostActionResult> trackEvent(TrackEventActionPayload payload) async {
    return _ok(ActionNames.trackEvent);
  }
}
