import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mini_program_contracts/mini_program_contracts.dart';
import 'package:mini_program_sdk/mini_program_sdk.dart';
import 'package:mini_program_ui/mini_program_ui.dart';

void main() {
  group('MpScreenValidator', () {
    test('accepts JSON generated by mini_program_ui', () {
      const validator = MpScreenValidator();
      validator.validate(_uiGeneratedScreen(), expectedScreenId: 'coupon_home');
    });

    test('rejects malformed Mp screen JSON', () {
      final cases = <String, Map<String, dynamic>>{
        'bad schema': _screenWith((json) {
          json['schemaVersion'] = 2;
        }),
        'screen mismatch': _screenWith((json) {
          json['screenId'] = 'other_home';
        }),
        'unsupported node': _screenWith((json) {
          (json['root'] as Map<String, dynamic>)['type'] = 'video';
        }),
        'malformed props': _screenWith((json) {
          ((json['root'] as Map<String, dynamic>)['children'] as List)
                  .cast<Map<String, dynamic>>()
                  .last['props'] =
              'bad';
        }),
        'invalid action': _screenWith((json) {
          final button =
              ((json['root'] as Map<String, dynamic>)['children'] as List)
                  .cast<Map<String, dynamic>>()
                  .last;
          ((button['props'] as Map<String, dynamic>)['action']
                  as Map<String, dynamic>)['type'] =
              'host.run';
        }),
        'unsafe image url': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'image',
            'props': <String, dynamic>{'src': 'http://example.com/a.png'},
            'children': <Object?>[],
          };
        }),
        'too many children': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'column',
            'props': <String, dynamic>{},
            'children': List<Object?>.generate(
              MpScreenValidator.maxDirectChildren + 1,
              (index) => <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Item $index'},
                'children': <Object?>[],
              },
            ),
          };
        }),
      };

      for (final entry in cases.entries) {
        expect(
          () => const MpScreenValidator().validate(
            entry.value,
            expectedScreenId: 'coupon_home',
          ),
          throwsA(isA<MiniProgramRenderException>()),
          reason: entry.key,
        );
      }
    });
  });

  group('MpScreenRenderer', () {
    testWidgets('renders basic Mp nodes with Flutter widgets', (tester) async {
      await tester.pumpWidget(
        MaterialApp(
          home: Builder(
            builder: (context) {
              return const MpScreenRenderer().render(
                MiniProgramRenderRequest(
                  context: context,
                  manifest: _mpManifest,
                  screenId: 'coupon_home',
                  screenJson: _fullBasicScreen,
                  logger: DebugPrintSdkLogger(),
                ),
              );
            },
          ),
        ),
      );

      expect(find.text('Publisher account'), findsOneWidget);
      expect(find.text('Sign in to continue'), findsOneWidget);
      expect(find.text('Inside card'), findsOneWidget);
      expect(find.text('Sign in'), findsOneWidget);
      expect(find.text('Cancel'), findsOneWidget);
      expect(find.byType(Image), findsOneWidget);
    });

    testWidgets('auth button opens the SDK email auth sheet without tokens', (
      tester,
    ) async {
      final controller = MiniProgramAuthController(
        store: InMemoryMiniProgramAuthStore(),
        clock: () => DateTime.utc(2026, 6, 3, 12),
      );
      final connector = _AuthConnector();
      final backendStore = MiniProgramBackendStore();

      await tester.pumpWidget(
        MaterialApp(
          home: MiniProgramSdkScope(
            miniProgramId: 'coupon',
            hostBridge: _NoopHostBridge(),
            capabilityRegistry: CapabilityRegistry(const <CapabilityId>[
              CapabilityIds.auth,
            ]),
            backendConnector: connector,
            authController: controller,
            backendStore: backendStore,
            featureFlagEvaluator: const AllowAllFeatureFlagEvaluator(),
            logger: const DebugPrintSdkLogger(),
            openMiniProgramScreen: (_, _) async => _ok('openMiniProgramScreen'),
            resetMiniProgramStack: (_, _) async => _ok('resetMiniProgramStack'),
            replaceMiniProgramScreen: (_, _) async =>
                _ok('replaceMiniProgramScreen'),
            popMiniProgramScreen: (_, _) async => _ok('popMiniProgramScreen'),
            popToMiniProgramRoot: (_, _) async => _ok('popToMiniProgramRoot'),
            popToMiniProgramScreen: (_, _) async =>
                _ok('popToMiniProgramScreen'),
            child: Builder(
              builder: (context) {
                return const MpScreenRenderer().render(
                  MiniProgramRenderRequest(
                    context: context,
                    manifest: _mpManifest,
                    screenId: 'coupon_home',
                    screenJson: _uiGeneratedScreenConst,
                    logger: DebugPrintSdkLogger(),
                  ),
                );
              },
            ),
          ),
        ),
      );

      await tester.tap(find.text('Sign in'));
      await tester.pumpAndSettle();

      expect(find.text('Email'), findsOneWidget);
      expect(find.text('Password'), findsOneWidget);
      expect(find.textContaining('id-token'), findsNothing);
      expect(find.textContaining('refresh-token'), findsNothing);

      backendStore.dispose();
    });
  });
}

const MiniProgramManifest _mpManifest = MiniProgramManifest(
  id: 'coupon',
  version: '1.0.0',
  entry: 'coupon_home',
  contractVersion: '1.0.0',
  sdkVersionRange: SdkVersionRange(value: '>=1.0.0 <2.0.0'),
  requiredCapabilities: <CapabilityId>[CapabilityIds.auth],
  screenFormat: MiniProgramScreenFormats.mp,
  screenSchemaVersion: 1,
);

Map<String, dynamic> _uiGeneratedScreen() {
  final miniProgram = MpProgram(
    screens: <String, MpScreenBuilder>{
      'coupon_home': () => Mp.column(
        children: <MpNode>[
          Mp.heading('Publisher account'),
          Mp.text('Sign in to continue'),
          Mp.primaryButton(label: 'Sign in', action: Mp.auth.showEmailAuth()),
        ],
      ),
    },
  );
  return _jsonMap(miniProgram.buildScreensJson()['coupon_home']!);
}

Map<String, dynamic> _screenWith(void Function(Map<String, dynamic>) mutate) {
  final json = _uiGeneratedScreen();
  mutate(json);
  return json;
}

Map<String, dynamic> _jsonMap(Map<String, Object?> json) {
  return Map<String, dynamic>.from(jsonDecode(jsonEncode(json)) as Map);
}

const Map<String, dynamic> _uiGeneratedScreenConst = <String, dynamic>{
  'schemaVersion': 1,
  'screenId': 'coupon_home',
  'root': <String, dynamic>{
    'type': 'column',
    'props': <String, dynamic>{},
    'children': <Object?>[
      <String, dynamic>{
        'type': 'primaryButton',
        'props': <String, dynamic>{
          'label': 'Sign in',
          'action': <String, dynamic>{
            'type': 'auth.showEmailAuth',
            'props': <String, dynamic>{},
          },
        },
        'children': <Object?>[],
      },
    ],
  },
};

const Map<String, dynamic> _fullBasicScreen = <String, dynamic>{
  'schemaVersion': 1,
  'screenId': 'coupon_home',
  'root': <String, dynamic>{
    'type': 'column',
    'props': <String, dynamic>{},
    'children': <Object?>[
      <String, dynamic>{
        'type': 'heading',
        'props': <String, dynamic>{'data': 'Publisher account'},
        'children': <Object?>[],
      },
      <String, dynamic>{
        'type': 'text',
        'props': <String, dynamic>{'data': 'Sign in to continue'},
        'children': <Object?>[],
      },
      <String, dynamic>{
        'type': 'row',
        'props': <String, dynamic>{},
        'children': <Object?>[
          <String, dynamic>{
            'type': 'sizedBox',
            'props': <String, dynamic>{'width': 8, 'height': 8},
            'children': <Object?>[],
          },
          <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Inline'},
            'children': <Object?>[],
          },
        ],
      },
      <String, dynamic>{
        'type': 'image',
        'props': <String, dynamic>{
          'src': 'https://example.com/coupon.png',
          'alt': 'Coupon image',
        },
        'children': <Object?>[],
      },
      <String, dynamic>{
        'type': 'card',
        'props': <String, dynamic>{},
        'children': <Object?>[
          <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Inside card'},
            'children': <Object?>[],
          },
        ],
      },
      <String, dynamic>{
        'type': 'primaryButton',
        'props': <String, dynamic>{
          'label': 'Sign in',
          'action': <String, dynamic>{
            'type': 'auth.showEmailAuth',
            'props': <String, dynamic>{},
          },
        },
        'children': <Object?>[],
      },
      <String, dynamic>{
        'type': 'secondaryButton',
        'props': <String, dynamic>{
          'label': 'Cancel',
          'action': <String, dynamic>{
            'type': 'auth.showEmailAuth',
            'props': <String, dynamic>{},
          },
        },
        'children': <Object?>[],
      },
    ],
  },
};

HostActionResult _ok(String actionName) {
  return HostActionResult.success(actionName: actionName);
}

class _AuthConnector implements MiniProgramBackendConnector {
  @override
  Future<MiniProgramBackendResult> call(
    MiniProgramBackendRequest request,
  ) async {
    return MiniProgramBackendResult.success(
      endpoint: request.endpoint,
      method: request.method,
      data: const <String, dynamic>{
        'authenticated': true,
        'user': <String, dynamic>{'uid': 'user-1', 'email': 'user@example.com'},
        'idToken': 'id-token',
        'refreshToken': 'refresh-token',
        'expiresIn': 3600,
      },
    );
  }
}

class _NoopHostBridge implements HostBridge {
  @override
  Future<HostActionResult> callSecureApi(
    CallSecureApiActionPayload payload,
  ) async {
    return _ok(ActionNames.callSecureApi);
  }

  @override
  Future<HostActionResult> openNativeScreen(
    OpenNativeScreenActionPayload payload,
  ) async {
    return _ok(ActionNames.openNativeScreen);
  }

  @override
  Future<HostActionResult> trackEvent(TrackEventActionPayload payload) async {
    return _ok(ActionNames.trackEvent);
  }
}
