part of '../mp_screen_renderer_test.dart';

void _mpScreenValidatorTests() {
  group('MpScreenValidator', () {
    test('accepts JSON generated by mini_program_ui', () {
      const validator = MpScreenValidator();
      validator.validate(_uiGeneratedScreen(), expectedScreenId: 'coupon_home');
    });

    test('accepts author-generated runtime parity JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.column(
              children: <MpNode>[
                Mp.authBuilder(
                  signedOut: Mp.primaryButton(
                    label: 'Sign in',
                    action: Mp.auth.showEmailAuth(),
                  ),
                  signedIn: Mp.secondaryButton(
                    label: 'Sign out',
                    action: Mp.auth.signOut(),
                  ),
                ),
                Mp.backendBuilder(
                  requestId: 'home',
                  endpoint: 'home/bootstrap',
                  child: Mp.text('{{backend.home.data.title}}'),
                ),
                Mp.pagedBackendBuilder(
                  requestId: 'coupons',
                  endpoint: 'coupons/page',
                  itemTemplate: Mp.text('{{item.title}}'),
                  loadMore: Mp.secondaryButton(
                    label: 'Load more',
                    action: Mp.backend.loadMore(requestId: 'coupons'),
                  ),
                ),
                Mp.primaryButton(
                  label: 'Details',
                  action: Mp.navigation.openScreen('coupon_details'),
                ),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts generated state transformation and math actions', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.column(
              children: <MpNode>[
                Mp.primaryButton(
                  label: 'Calculate',
                  action: Mp.action.sequence(<MpAction>[
                    Mp.state.setDefault('calc.memory', 0),
                    Mp.state.appendText('calc.expression', '7'),
                    Mp.state.increment(
                      'calc.memory',
                      by: '{{state.calc.result}}',
                      min: 0,
                    ),
                    Mp.state.decrement('calc.memory', by: 1),
                    Mp.state.copy(
                      from: 'calc.memory',
                      to: 'calc.expression',
                      convertTo: 'text',
                    ),
                    Mp.state.toggle('calc.scientific'),
                    Mp.state.patch(
                      const <String, Object?>{'calc.ready': true},
                      remove: const <String>['calc.stale'],
                    ),
                    Mp.math.evaluate(
                      expression: '{{state.calc.expression}}',
                      targetState: 'calc.result',
                      errorState: 'calc.error',
                    ),
                    Mp.state.listPrepend(
                      'calc.history',
                      '{{state.calc.result}}',
                      maxItems: 50,
                    ),
                    Mp.cache.info(targetState: 'calc.cache_info'),
                  ]),
                ),
                Mp.initialize(
                  actions: <MpAction>[
                    Mp.state.setDefault('screen.ready', true),
                  ],
                  statusState: 'screen.status',
                  errorState: 'screen.error',
                  child: Mp.stateScope(
                    prefix: 'screen.form',
                    child: Mp.text('Initialized'),
                  ),
                ),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts generated condition, ifElse, and countdown primitives', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.timer.countdown(
              duration: const Duration(seconds: 10),
              running: '{{state.screen.running}}',
              restartToken: '{{state.screen.content_id}}',
              remainingState: 'screen.remaining',
              onComplete: Mp.action.ifElse(
                condition: '{{state.screen.should_advance}}',
                thenAction: Mp.state.set('screen.status', 'advanced'),
                elseAction: Mp.state.set('screen.status', 'expired'),
              ),
              child: Mp.condition(
                condition: '{{state.screen.ready}}',
                whenTrue: Mp.text('Ready'),
                whenFalse: Mp.text('Waiting'),
              ),
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts generated scoped reusable actions', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.actionScope(
              actions: <String, MpAction>{
                'nextStep': Mp.action.sequence(<MpAction>[
                  Mp.state.increment('flow.step'),
                  Mp.state.set('flow.snapshot', '{{state.flow.step}}'),
                ]),
              },
              child: Mp.button(
                label: 'Next',
                action: Mp.action.call('nextStep'),
              ),
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('rejects malformed condition, ifElse, and countdown primitives', () {
      final invalidCondition = _screenWith((json) {
        json['root'] = <String, dynamic>{
          'type': 'condition',
          'props': <String, dynamic>{
            'condition': 'prefix {{state.ready}}',
            'whenTrue': <String, dynamic>{
              'type': 'text',
              'props': <String, dynamic>{'data': 'Ready'},
              'children': <Object?>[],
            },
          },
          'children': <Object?>[],
        };
      });
      final invalidIfElse = _cacheActionScreen('action.ifElse', {
        'condition': 1,
        'then': <String, dynamic>{
          'type': 'state.set',
          'props': <String, dynamic>{'key': 'status', 'value': 'yes'},
        },
        'else': <String, dynamic>{
          'type': 'state.set',
          'props': <String, dynamic>{'key': 'status', 'value': 'no'},
        },
      });
      final invalidCountdownDuration = _screenWith((json) {
        json['root'] = <String, dynamic>{
          'type': 'countdown',
          'props': <String, dynamic>{
            'durationMs': MpScreenValidator.maxCountdownDurationMs + 1,
            'remainingState': 'timer.remaining',
          },
          'children': <Object?>[
            <String, dynamic>{
              'type': 'text',
              'props': <String, dynamic>{'data': 'Timer'},
              'children': <Object?>[],
            },
          ],
        };
      });
      final inertCountdown = _screenWith((json) {
        json['root'] = <String, dynamic>{
          'type': 'countdown',
          'props': <String, dynamic>{'durationMs': 1000},
          'children': <Object?>[
            <String, dynamic>{
              'type': 'text',
              'props': <String, dynamic>{'data': 'Timer'},
              'children': <Object?>[],
            },
          ],
        };
      });

      for (final screen in <Map<String, dynamic>>[
        invalidCondition,
        invalidIfElse,
        invalidCountdownDuration,
        inertCountdown,
      ]) {
        expect(
          () => const MpScreenValidator().validate(
            screen,
            expectedScreenId: 'coupon_home',
          ),
          throwsA(isA<MiniProgramRenderException>()),
        );
      }
    });

    test('rejects malformed state transformation and math actions', () {
      final cases = <String, Map<String, dynamic>>{
        'text limit': _cacheActionScreen('state.appendText', {
          'key': 'calc.expression',
          'text': '1',
          'maxLength': 65537,
        }),
        'list index': _cacheActionScreen('state.listRemoveAt', {
          'key': 'items',
          'index': 'first',
        }),
        'numeric operand': _cacheActionScreen('state.increment', {
          'key': 'count',
          'by': 'one',
        }),
        'numeric bounds': _cacheActionScreen('state.decrement', {
          'key': 'count',
          'min': 10,
          'max': 1,
        }),
        'copy conversion': _cacheActionScreen('state.copy', {
          'from': 'source',
          'to': 'target',
          'convertTo': 'json',
        }),
        'toggle default': _cacheActionScreen('state.toggle', {
          'key': 'enabled',
          'defaultValue': 'yes',
        }),
        'patch overlap': _cacheActionScreen('state.patch', {
          'values': <String, Object?>{
            'profile': <String, Object?>{},
            'profile.name': 'Ada',
          },
        }),
        'math expression': _cacheActionScreen('math.evaluate', {
          'expression': '',
          'targetState': 'result',
        }),
        'math precision': _cacheActionScreen('math.evaluate', {
          'expression': '1 + 1',
          'targetState': 'result',
          'precision': 16,
        }),
        'math comparison': _cacheActionScreen('math.compare', {
          'left': 1,
          'right': 2,
          'comparison': 'symbolic',
          'targetState': 'result',
        }),
        'math random seed': _cacheActionScreen('math.randomInt', {
          'min': 1,
          'max': 2,
          'seed': 'random',
          'targetState': 'result',
        }),
        'math aggregate values': _cacheActionScreen('math.aggregate', {
          'values': 'not-a-binding',
          'operation': 'sum',
          'targetState': 'result',
        }),
      };

      for (final entry in cases.entries) {
        expect(
          () => const MpScreenValidator().validate(
            entry.value,
            expectedScreenId: 'coupon_home',
          ),
          throwsA(isA<MiniProgramRenderException>()),
          reason: entry.key,
        );
      }
    });

    test('rejects malformed initialize and stateScope nodes', () {
      final initialize = _screenWith((json) {
        json['root'] = <String, dynamic>{
          'type': 'initialize',
          'props': <String, dynamic>{
            'actions': <Object?>[
              <String, dynamic>{
                'type': 'state.set',
                'props': <String, dynamic>{'key': 'ready', 'value': true},
              },
            ],
            'retry': 11,
          },
          'children': <Object?>[
            <String, dynamic>{
              'type': 'text',
              'props': <String, dynamic>{'data': 'Ready'},
              'children': <Object?>[],
            },
          ],
        };
      });
      expect(
        () => const MpScreenValidator().validate(
          initialize,
          expectedScreenId: 'coupon_home',
        ),
        throwsA(isA<MiniProgramRenderException>()),
      );

      final stateScope = _screenWith((json) {
        json['root'] = <String, dynamic>{
          'type': 'stateScope',
          'props': <String, dynamic>{'prefix': 'auth.token'},
          'children': <Object?>[
            <String, dynamic>{
              'type': 'text',
              'props': <String, dynamic>{'data': 'Scoped'},
              'children': <Object?>[],
            },
          ],
        };
      });
      expect(
        () => const MpScreenValidator().validate(
          stateScope,
          expectedScreenId: 'coupon_home',
        ),
        throwsA(isA<MiniProgramRenderException>()),
      );

      final actionScope = _screenWith((json) {
        json['root'] = <String, dynamic>{
          'type': 'actionScope',
          'props': <String, dynamic>{
            'actions': <String, dynamic>{
              'invalid-name': <String, dynamic>{
                'type': 'state.set',
                'props': <String, dynamic>{'key': 'ready', 'value': true},
              },
            },
          },
          'children': <Object?>[
            <String, dynamic>{
              'type': 'text',
              'props': <String, dynamic>{'data': 'Scoped'},
              'children': <Object?>[],
            },
          ],
        };
      });
      expect(
        () => const MpScreenValidator().validate(
          actionScope,
          expectedScreenId: 'coupon_home',
        ),
        throwsA(isA<MiniProgramRenderException>()),
      );

      final tooManyActions = _screenWith((json) {
        json['root'] = <String, dynamic>{
          'type': 'actionScope',
          'props': <String, dynamic>{
            'actions': <String, dynamic>{
              for (
                var index = 0;
                index <= MpScreenValidator.maxActionDefinitions;
                index += 1
              )
                'action$index': <String, dynamic>{
                  'type': 'state.set',
                  'props': <String, dynamic>{'key': 'ready', 'value': true},
                },
            },
          },
          'children': <Object?>[
            <String, dynamic>{
              'type': 'text',
              'props': <String, dynamic>{'data': 'Scoped'},
              'children': <Object?>[],
            },
          ],
        };
      });
      expect(
        () => const MpScreenValidator().validate(
          tooManyActions,
          expectedScreenId: 'coupon_home',
        ),
        throwsA(isA<MiniProgramRenderException>()),
      );
    });

    test('accepts author-generated form JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.form(
              children: <MpNode>[
                Mp.textInput(
                  name: 'full_name',
                  label: 'Full name',
                  required: true,
                  minLength: 2,
                ),
                Mp.textArea(name: 'essay', label: 'Essay', maxLength: 500),
                Mp.dropdown(
                  name: 'program',
                  label: 'Program',
                  options: const <MpOption>[
                    MpOption(value: 'stem', label: 'STEM'),
                    MpOption(value: 'arts', label: 'Arts'),
                  ],
                ),
                Mp.radioGroup(
                  name: 'level',
                  label: 'Level',
                  options: const <MpOption>[
                    MpOption(value: 'undergraduate', label: 'Undergraduate'),
                    MpOption(value: 'graduate', label: 'Graduate'),
                  ],
                  required: true,
                ),
                Mp.checkbox(
                  name: 'terms',
                  label: 'I confirm',
                  requiredTrue: true,
                ),
                Mp.formSubmit(
                  label: 'Submit',
                  endpoint: 'applications/submit',
                  onSuccess: Mp.toast(message: 'Submitted', durationMs: 1),
                  onError: Mp.dialog(message: 'Failed'),
                ),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated state and router JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.column(
              children: <MpNode>[
                Mp.stateBuilder(
                  keys: const <String>['count'],
                  child: Mp.text('Count: {{state.count}}'),
                ),
                Mp.primaryButton(
                  label: 'Increment',
                  action: Mp.state.increment('count'),
                ),
                Mp.secondaryButton(
                  label: 'Detail',
                  action: Mp.router.push(
                    'coupon_detail',
                    params: const <String, Object?>{'productId': 'p1'},
                  ),
                ),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated core design widget JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.column(
              children: <MpNode>[
                Mp.padding(all: 12, child: Mp.text('Padded')),
                Mp.container(
                  paddingAll: 8,
                  backgroundColor: '#FFFFFFFF',
                  borderColor: '#E5E7EB',
                  borderWidth: 1,
                  borderRadius: 8,
                  child: Mp.text('Box'),
                ),
                Mp.scrollView(
                  paddingVertical: 4,
                  child: Mp.column(children: <MpNode>[Mp.text('Scrollable')]),
                ),
                Mp.divider(),
                Mp.icon('settings', semanticLabel: 'Settings'),
                Mp.listTile(
                  title: 'Profile',
                  subtitle: 'Manage account',
                  leadingIcon: 'person',
                  badge: 'New',
                  action: Mp.state.set('selected.profile', true),
                ),
                Mp.chip(
                  label: 'Featured',
                  tone: 'success',
                  leadingIcon: 'star',
                  action: Mp.state.set('filter.featured', true),
                ),
                Mp.badge(label: 'Beta', tone: 'warning'),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated future display and layout widget JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.column(
              children: <MpNode>[
                Mp.alert(title: 'Heads up', message: 'Review settings'),
                Mp.avatar(initials: 'MH', semanticLabel: 'Mehedi'),
                Mp.grid(children: <MpNode>[Mp.text('One'), Mp.text('Two')]),
                Mp.wrap(
                  children: <MpNode>[
                    Mp.chip(label: 'Fast'),
                    Mp.badge(label: 'New'),
                  ],
                ),
                Mp.progress(value: 0.4, label: 'Loading'),
                Mp.emptyState(
                  title: 'No coupons',
                  actionLabel: 'Retry',
                  action: Mp.state.set('empty.retry', true),
                ),
                Mp.section(
                  title: 'Featured',
                  child: Mp.text('Section body'),
                  actionLabel: 'View all',
                  action: Mp.state.set('section.more', true),
                ),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated safe layout primitive JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.column(
              children: <MpNode>[
                Mp.align(alignment: 'bottomRight', child: Mp.text('Aligned')),
                Mp.center(child: Mp.text('Centered')),
                Mp.row(
                  children: <MpNode>[
                    Mp.text('Left'),
                    Mp.spacer(flex: 2),
                    Mp.text('Right'),
                  ],
                ),
                Mp.listView(
                  spacing: 6,
                  paddingVertical: 4,
                  children: <MpNode>[Mp.text('One'), Mp.text('Two')],
                ),
                Mp.safeArea(left: false, bottom: false, child: Mp.text('Safe')),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated visual layout primitive JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.column(
              children: <MpNode>[
                Mp.visibility(
                  visible: false,
                  maintainSize: true,
                  child: Mp.text('Hidden'),
                ),
                Mp.opacity(opacity: 0.5, child: Mp.text('Faded')),
                Mp.aspectRatio(aspectRatio: 2, child: Mp.text('Ratio')),
                Mp.stack(
                  alignment: 'bottomRight',
                  clip: false,
                  children: <MpNode>[
                    Mp.text('Base'),
                    Mp.positioned(
                      top: 8,
                      right: 8,
                      child: Mp.badge(label: 'New'),
                    ),
                  ],
                ),
                Mp.positioned(top: 4, child: Mp.text('Fallback')),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated flex sizing primitive JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.column(
              children: <MpNode>[
                Mp.row(
                  children: <MpNode>[
                    Mp.expanded(flex: 2, child: Mp.text('Expanded')),
                    Mp.flexible(
                      flex: 3,
                      fit: 'tight',
                      child: Mp.text('Flexible'),
                    ),
                  ],
                ),
                Mp.flexible(child: Mp.text('Fallback')),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated lightweight text style JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.column(
              children: <MpNode>[
                Mp.text(
                  'বাংলা লেখা এখানে',
                  size: 16,
                  color: '#111827',
                  weight: 'semibold',
                  align: 'center',
                  maxLines: 2,
                  overflow: 'ellipsis',
                  lineHeight: 1.4,
                  locale: 'bn',
                  variant: 'title',
                ),
                Mp.heading(
                  'مرحبا',
                  level: 2,
                  textDirection: 'auto',
                  variant: 'section_title',
                ),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated lightweight theme JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.theme(
              colors: const <String, String>{
                'text': '#111827',
                'accent': '#2563EB',
              },
              typography: const <String, Map<String, Object?>>{
                'title': <String, Object?>{
                  'size': 20,
                  'weight': 'bold',
                  'lineHeight': 1.2,
                  'color': 'text',
                },
                'caption': <String, Object?>{
                  'size': 12,
                  'weight': 'regular',
                  'lineHeight': 1.35,
                  'color': '#6B7280',
                },
              },
              child: Mp.column(
                children: <MpNode>[
                  Mp.text('Theme title', variant: 'title'),
                  Mp.heading('Theme caption', level: 4, variant: 'caption'),
                ],
              ),
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated async image JSON', () {
      const base64Image =
          'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=';
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.column(
              children: <MpNode>[
                Mp.image(
                  src: 'https://example.com/a.png',
                  headers: const <String, String>{'x-image': 'product'},
                  semanticLabel: 'Product image',
                  width: 120,
                  height: 120,
                ),
                Mp.image(
                  src: 'assets/logo.png',
                  source: MpImageSource.asset,
                  fit: MpImageFit.contain,
                  alt: 'Logo asset',
                ),
                Mp.image(
                  src: base64Image,
                  source: MpImageSource.base64,
                  placeholder: Mp.text('Loading image...'),
                  error: Mp.text('Image failed'),
                  fadeInDuration: const Duration(milliseconds: 80),
                ),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated skeleton JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.column(
              children: <MpNode>[
                Mp.skeleton.box(),
                Mp.skeleton.box(width: 120, height: 120),
                Mp.skeleton.text(width: 200),
                Mp.skeleton.circle(size: 48),
                Mp.skeleton.card(width: 320),
                Mp.skeleton.list(count: 5),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated lazy section JSON', () {
      final screen = _lazySectionScreen(
        id: 'home_products',
        placeholder: Mp.skeleton.list(count: 3),
        error: Mp.text('Failed to load products'),
        cacheKey: 'products_page_1',
        targetState: 'products',
        statusState: 'products_lazy_status',
        ttl: const Duration(days: 1),
        retry: 1,
        actions: <MpAction>[
          Mp.backend.query(requestId: 'products_query', endpoint: '/products'),
        ],
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated lazy chunk JSON', () {
      final screen = _lazyChunkScreen(cacheKeyPrefix: 'rewards_chunk');

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated repeat JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.stateBuilder(
              keys: const <String>['area.results'],
              child: Mp.repeat(
                source: '{{state.area.results.items}}',
                itemTemplate: Mp.listTile(
                  title: '{{index}}. {{item.name}}',
                  subtitle: '{{item.lat}}, {{item.lon}}',
                ),
                empty: Mp.emptyState(title: 'No area found'),
                separator: Mp.divider(spacing: 0),
                limit: 20,
              ),
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated backend search input JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.searchInput(
              stateKey: 'area.query',
              targetState: 'area.results',
              statusState: 'area.search_status',
              errorState: 'area.search_error',
              endpoint: '/areas/search',
              hint: 'Search area',
              minLength: 2,
              limit: 20,
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts author-generated backend search action JSON', () {
      final screen = _jsonMap(
        MpProgram(
          screens: <String, MpScreenBuilder>{
            'coupon_home': () => Mp.column(
              children: <MpNode>[
                Mp.secondaryButton(
                  label: 'Clear',
                  action: Mp.search.clear(
                    queryState: 'area.query',
                    targetState: 'area.results',
                    statusState: 'area.search_status',
                    errorState: 'area.search_error',
                  ),
                ),
                Mp.secondaryButton(
                  label: 'Refresh',
                  action: Mp.search.refresh(
                    queryState: 'area.query',
                    targetState: 'area.results',
                    statusState: 'area.search_status',
                    errorState: 'area.search_error',
                    endpoint: '/areas/search',
                  ),
                ),
                Mp.secondaryButton(
                  label: 'Load more',
                  action: Mp.search.loadMore(
                    queryState: 'area.query',
                    targetState: 'area.results',
                    statusState: 'area.search_status',
                    errorState: 'area.search_error',
                    endpoint: '/areas/search',
                  ),
                ),
              ],
            ),
          },
        ).buildScreensJson()['coupon_home']!,
      );

      const MpScreenValidator().validate(
        screen,
        expectedScreenId: 'coupon_home',
      );
    });

    test('accepts cache action JSON', () {
      const MpScreenValidator().validate(
        _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'primaryButton',
            'props': <String, dynamic>{
              'label': 'Cache products',
              'action': <String, dynamic>{
                'type': 'sequence',
                'props': <String, dynamic>{
                  'steps': <Object?>[
                    <String, dynamic>{
                      'type': 'cache.set',
                      'props': <String, dynamic>{
                        'requestId': 'cache-set',
                        'key': 'products_page_1',
                        'bucket': 'data',
                        'value': <String, Object?>{'items': <Object?>[]},
                        'ttlMs': 86400000,
                        'priority': 'normal',
                      },
                    },
                    <String, dynamic>{
                      'type': 'cache.has',
                      'props': <String, dynamic>{
                        'key': 'products_page_1',
                        'targetState': 'cache.has_products',
                      },
                    },
                    <String, dynamic>{
                      'type': 'cache.get',
                      'props': <String, dynamic>{
                        'key': 'products_page_1',
                        'targetState': 'cache.products',
                        'skipMissing': true,
                      },
                    },
                    <String, dynamic>{
                      'type': 'cache.remove',
                      'props': <String, dynamic>{'key': 'products_page_1'},
                    },
                    <String, dynamic>{
                      'type': 'cache.clear',
                      'props': <String, dynamic>{'bucket': 'state'},
                    },
                  ],
                },
              },
            },
            'children': <Object?>[],
          };
        }),
        expectedScreenId: 'coupon_home',
      );
    });

    test('rejects malformed Mp screen JSON', () {
      final cases = <String, Map<String, dynamic>>{
        'bad schema': _screenWith((json) {
          json['schemaVersion'] = 2;
        }),
        'screen mismatch': _screenWith((json) {
          json['screenId'] = 'other_home';
        }),
        'unsupported node': _screenWith((json) {
          (json['root'] as Map<String, dynamic>)['type'] = 'video';
        }),
        'malformed props': _screenWith((json) {
          ((json['root'] as Map<String, dynamic>)['children'] as List)
                  .cast<Map<String, dynamic>>()
                  .last['props'] =
              'bad';
        }),
        'invalid action': _screenWith((json) {
          final button =
              ((json['root'] as Map<String, dynamic>)['children'] as List)
                  .cast<Map<String, dynamic>>()
                  .last;
          ((button['props'] as Map<String, dynamic>)['action']
                  as Map<String, dynamic>)['type'] =
              'host.run';
        }),
        'invalid network image scheme': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'image',
            'props': <String, dynamic>{
              'src': 'ftp://example.com/a.png',
              'source': 'network',
            },
            'children': <Object?>[],
          };
        }),
        'invalid image source': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'image',
            'props': <String, dynamic>{
              'src': 'assets/logo.png',
              'source': 'file',
            },
            'children': <Object?>[],
          };
        }),
        'invalid image fit': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'image',
            'props': <String, dynamic>{'src': 'assets/logo.png', 'fit': 'crop'},
            'children': <Object?>[],
          };
        }),
        'invalid image width': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'image',
            'props': <String, dynamic>{'src': 'assets/logo.png', 'width': 0},
            'children': <Object?>[],
          };
        }),
        'invalid image headers': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'image',
            'props': <String, dynamic>{
              'src': 'assets/logo.png',
              'headers': 'bad',
            },
            'children': <Object?>[],
          };
        }),
        'invalid image header value': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'image',
            'props': <String, dynamic>{
              'src': 'assets/logo.png',
              'headers': <String, dynamic>{'x-test': ''},
            },
            'children': <Object?>[],
          };
        }),
        'invalid base64 image': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'image',
            'props': <String, dynamic>{
              'src': 'not base64!',
              'source': 'base64',
            },
            'children': <Object?>[],
          };
        }),
        'image does not accept children': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'image',
            'props': <String, dynamic>{'src': 'assets/logo.png'},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Child'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'malformed image placeholder': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'image',
            'props': <String, dynamic>{
              'src': 'assets/logo.png',
              'placeholder': <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': ''},
                'children': <Object?>[],
              },
            },
            'children': <Object?>[],
          };
        }),
        'invalid skeleton variant': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'skeleton',
            'props': <String, dynamic>{'variant': 'shimmer'},
            'children': <Object?>[],
          };
        }),
        'invalid skeleton width': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'skeleton',
            'props': <String, dynamic>{'variant': 'box', 'width': 0},
            'children': <Object?>[],
          };
        }),
        'invalid skeleton token': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'skeleton',
            'props': <String, dynamic>{
              'variant': 'box',
              'colorToken': 'bad-token',
            },
            'children': <Object?>[],
          };
        }),
        'skeleton does not accept children': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'skeleton',
            'props': <String, dynamic>{'variant': 'box'},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Child'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'skeleton rejects incompatible props': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'skeleton',
            'props': <String, dynamic>{'variant': 'circle', 'radius': 8},
            'children': <Object?>[],
          };
        }),
        'skeleton circle requires size': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'skeleton',
            'props': <String, dynamic>{'variant': 'circle'},
            'children': <Object?>[],
          };
        }),
        'lazy requires one child': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'lazy',
            'props': <String, dynamic>{'id': 'products'},
            'children': <Object?>[],
          };
        }),
        'lazy rejects invalid action': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'lazy',
            'props': <String, dynamic>{
              'id': 'products',
              'actions': <Object?>[
                <String, dynamic>{
                  'type': 'network.get',
                  'props': <String, dynamic>{'path': '/products'},
                },
              ],
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Products'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'lazy rejects session bucket': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'lazy',
            'props': <String, dynamic>{'id': 'products', 'bucket': 'session'},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Products'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'lazy cache key requires targetState': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'lazy',
            'props': <String, dynamic>{
              'id': 'products',
              'cacheKey': 'products_page_1',
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Products'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'lazy rejects bad targetState': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'lazy',
            'props': <String, dynamic>{
              'id': 'products',
              'targetState': 'auth.token',
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Products'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'lazy rejects bad ttl': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'lazy',
            'props': <String, dynamic>{'id': 'products', 'ttlMs': 0},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Products'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'lazy rejects unknown prop': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'lazy',
            'props': <String, dynamic>{'id': 'products', 'path': '/products'},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Products'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'lazyChunk requires itemTemplate': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'lazyChunk',
            'props': <String, dynamic>{
              'id': 'products',
              'itemsState': 'products.items',
              'initialActions': <Object?>[_backendLoadMoreActionJson()],
              'loadMoreActions': <Object?>[_backendLoadMoreActionJson()],
            },
            'children': <Object?>[],
          };
        }),
        'lazyChunk requires initial actions': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'lazyChunk',
            'props': <String, dynamic>{
              'id': 'products',
              'itemsState': 'products.items',
              'itemTemplate': _textNode('{{item.title}}'),
              'initialActions': <Object?>[],
              'loadMoreActions': <Object?>[_backendLoadMoreActionJson()],
            },
            'children': <Object?>[],
          };
        }),
        'lazyChunk rejects bad state key': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'lazyChunk',
            'props': <String, dynamic>{
              'id': 'products',
              'itemsState': 'auth.token',
              'itemTemplate': _textNode('{{item.title}}'),
              'initialActions': <Object?>[_backendLoadMoreActionJson()],
              'loadMoreActions': <Object?>[_backendLoadMoreActionJson()],
            },
            'children': <Object?>[],
          };
        }),
        'lazyChunk rejects bad cache prefix': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'lazyChunk',
            'props': <String, dynamic>{
              'id': 'products',
              'itemsState': 'products.items',
              'cacheKeyPrefix': '../products',
              'itemTemplate': _textNode('{{item.title}}'),
              'initialActions': <Object?>[_backendLoadMoreActionJson()],
              'loadMoreActions': <Object?>[_backendLoadMoreActionJson()],
            },
            'children': <Object?>[],
          };
        }),
        'lazyChunk rejects unknown prop': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'lazyChunk',
            'props': <String, dynamic>{
              'id': 'products',
              'itemsState': 'products.items',
              'endpoint': '/products',
              'itemTemplate': _textNode('{{item.title}}'),
              'initialActions': <Object?>[_backendLoadMoreActionJson()],
              'loadMoreActions': <Object?>[_backendLoadMoreActionJson()],
            },
            'children': <Object?>[],
          };
        }),
        'lazy chunk load more rejects missing id': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'secondaryButton',
            'props': <String, dynamic>{
              'label': 'Load more',
              'action': <String, dynamic>{
                'type': 'lazy.chunk.loadMore',
                'props': <String, dynamic>{},
              },
            },
            'children': <Object?>[],
          };
        }),
        'repeat requires itemTemplate': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'repeat',
            'props': <String, dynamic>{'source': '{{state.items}}'},
            'children': <Object?>[],
          };
        }),
        'repeat rejects normal children': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'repeat',
            'props': <String, dynamic>{
              'source': '{{state.items}}',
              'itemTemplate': <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': '{{item.name}}'},
                'children': <Object?>[],
              },
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Wrong'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'repeat rejects non-binding source': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'repeat',
            'props': <String, dynamic>{
              'source': 'state.items',
              'itemTemplate': <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': '{{item.name}}'},
                'children': <Object?>[],
              },
            },
            'children': <Object?>[],
          };
        }),
        'repeat rejects partial binding source': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'repeat',
            'props': <String, dynamic>{
              'source': 'Items: {{state.items}}',
              'itemTemplate': <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': '{{item.name}}'},
                'children': <Object?>[],
              },
            },
            'children': <Object?>[],
          };
        }),
        'repeat rejects bad spacing': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'repeat',
            'props': <String, dynamic>{
              'source': '{{state.items}}',
              'spacing': -1,
              'itemTemplate': <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': '{{item.name}}'},
                'children': <Object?>[],
              },
            },
            'children': <Object?>[],
          };
        }),
        'repeat rejects bad limit': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'repeat',
            'props': <String, dynamic>{
              'source': '{{state.items}}',
              'limit': 501,
              'itemTemplate': <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': '{{item.name}}'},
                'children': <Object?>[],
              },
            },
            'children': <Object?>[],
          };
        }),
        'repeat rejects unknown prop': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'repeat',
            'props': <String, dynamic>{
              'source': '{{state.items}}',
              'itemName': 'area',
              'itemTemplate': <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': '{{item.name}}'},
                'children': <Object?>[],
              },
            },
            'children': <Object?>[],
          };
        }),
        'searchInput rejects bad state key': _screenWith((json) {
          json['root'] = _searchInputJson(<String, dynamic>{
            'stateKey': 'Area.query',
          });
        }),
        'searchInput rejects bound endpoint': _screenWith((json) {
          json['root'] = _searchInputJson(<String, dynamic>{
            'endpoint': '{{state.endpoint}}',
          });
        }),
        'searchInput rejects bad method': _screenWith((json) {
          json['root'] = _searchInputJson(<String, dynamic>{'method': 'PATCH'});
        }),
        'searchInput rejects bad query param': _screenWith((json) {
          json['root'] = _searchInputJson(<String, dynamic>{
            'queryParam': 'bad-param',
          });
        }),
        'searchInput rejects bad min length': _screenWith((json) {
          json['root'] = _searchInputJson(<String, dynamic>{'minLength': -1});
        }),
        'searchInput rejects bad limit': _screenWith((json) {
          json['root'] = _searchInputJson(<String, dynamic>{'limit': 101});
        }),
        'searchInput rejects bad debounce': _screenWith((json) {
          json['root'] = _searchInputJson(<String, dynamic>{'debounceMs': -1});
        }),
        'searchInput rejects unknown prop': _screenWith((json) {
          json['root'] = _searchInputJson(<String, dynamic>{'path': '/areas'});
        }),
        'searchInput rejects normal children': _screenWith((json) {
          json['root'] = _searchInputJson(
            const <String, dynamic>{},
            children: <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Wrong'},
                'children': <Object?>[],
              },
            ],
          );
        }),
        'search.loadMore rejects bad query state': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchLoadMoreActionJson(<String, dynamic>{
              'queryState': 'Area.query',
            }),
          );
        }),
        'search.loadMore rejects bound endpoint': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchLoadMoreActionJson(<String, dynamic>{
              'endpoint': '{{state.endpoint}}',
            }),
          );
        }),
        'search.loadMore rejects bad method': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchLoadMoreActionJson(<String, dynamic>{'method': 'PATCH'}),
          );
        }),
        'search.loadMore rejects bad param': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchLoadMoreActionJson(<String, dynamic>{
              'cursorParam': 'bad-param',
            }),
          );
        }),
        'search.loadMore rejects bad limit': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchLoadMoreActionJson(<String, dynamic>{'limit': 101}),
          );
        }),
        'search.loadMore rejects bad skip flag': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchLoadMoreActionJson(<String, dynamic>{
              'skipWhenNoQuery': 'yes',
            }),
          );
        }),
        'search.loadMore rejects unknown prop': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchLoadMoreActionJson(<String, dynamic>{'path': '/areas'}),
          );
        }),
        'search.clear rejects bad query state': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchClearActionJson(<String, dynamic>{
              'queryState': 'Area.query',
            }),
          );
        }),
        'search.clear rejects unknown prop': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchClearActionJson(<String, dynamic>{'endpoint': '/areas'}),
          );
        }),
        'search.refresh rejects bad target state': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchRefreshActionJson(<String, dynamic>{
              'targetState': 'auth.token',
            }),
          );
        }),
        'search.refresh rejects bound endpoint': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchRefreshActionJson(<String, dynamic>{
              'endpoint': '{{state.endpoint}}',
            }),
          );
        }),
        'search.refresh rejects bad method': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchRefreshActionJson(<String, dynamic>{'method': 'PATCH'}),
          );
        }),
        'search.refresh rejects bad param': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchRefreshActionJson(<String, dynamic>{
              'limitParam': 'bad-param',
            }),
          );
        }),
        'search.refresh rejects bad limit': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchRefreshActionJson(<String, dynamic>{'limit': 101}),
          );
        }),
        'search.refresh rejects bad skip flag': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchRefreshActionJson(<String, dynamic>{
              'skipWhenNoQuery': 'yes',
            }),
          );
        }),
        'search.refresh rejects unknown prop': _screenWith((json) {
          json['root'] = _actionButtonJson(
            _searchRefreshActionJson(<String, dynamic>{'path': '/areas'}),
          );
        }),
        'too many children': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'column',
            'props': <String, dynamic>{},
            'children': List<Object?>.generate(
              MpScreenValidator.maxDirectChildren + 1,
              (index) => <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Item $index'},
                'children': <Object?>[],
              },
            ),
          };
        }),
        'unsafe binding path': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': '{{auth.idToken}}'},
            'children': <Object?>[],
          };
        }),
        'unsupported binding root': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': '{{secrets.value}}'},
            'children': <Object?>[],
          };
        }),
        'empty text data': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': ''},
            'children': <Object?>[],
          };
        }),
        'invalid text size': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Hi', 'size': 0},
            'children': <Object?>[],
          };
        }),
        'invalid text color': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Hi', 'color': '#FFF'},
            'children': <Object?>[],
          };
        }),
        'invalid text weight': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Hi', 'weight': 'heavy'},
            'children': <Object?>[],
          };
        }),
        'invalid text align': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Hi', 'align': 'middle'},
            'children': <Object?>[],
          };
        }),
        'invalid text overflow': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Hi', 'overflow': 'truncate'},
            'children': <Object?>[],
          };
        }),
        'invalid text maxLines': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Hi', 'maxLines': 0},
            'children': <Object?>[],
          };
        }),
        'invalid text lineHeight': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Hi', 'lineHeight': 0},
            'children': <Object?>[],
          };
        }),
        'invalid text direction': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Hi', 'textDirection': 'both'},
            'children': <Object?>[],
          };
        }),
        'invalid text locale': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Hi', 'locale': 'en_us'},
            'children': <Object?>[],
          };
        }),
        'invalid text variant': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Hi', 'variant': ''},
            'children': <Object?>[],
          };
        }),
        'invalid text softWrap': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Hi', 'softWrap': 'no'},
            'children': <Object?>[],
          };
        }),
        'invalid heading level': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'heading',
            'props': <String, dynamic>{'data': 'Hi', 'level': 7},
            'children': <Object?>[],
          };
        }),
        'text does not support heading level': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'text',
            'props': <String, dynamic>{'data': 'Hi', 'level': 2},
            'children': <Object?>[],
          };
        }),
        'theme colors must be object': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'theme',
            'props': <String, dynamic>{'colors': 'bad'},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'theme color must be hex': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'theme',
            'props': <String, dynamic>{
              'colors': <String, dynamic>{'text': 'red'},
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'theme token name must be valid': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'theme',
            'props': <String, dynamic>{
              'colors': <String, dynamic>{'bad-token': '#FFFFFF'},
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'theme typography must be object': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'theme',
            'props': <String, dynamic>{'typography': 'bad'},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'theme typography variant must be valid': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'theme',
            'props': <String, dynamic>{
              'typography': <String, dynamic>{
                '': <String, dynamic>{'size': 16},
              },
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'theme typography field must be supported': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'theme',
            'props': <String, dynamic>{
              'typography': <String, dynamic>{
                'title': <String, dynamic>{'fontFamily': 'Inter'},
              },
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'theme typography size must be positive': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'theme',
            'props': <String, dynamic>{
              'typography': <String, dynamic>{
                'title': <String, dynamic>{'size': 0},
              },
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'theme typography weight must be valid': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'theme',
            'props': <String, dynamic>{
              'typography': <String, dynamic>{
                'title': <String, dynamic>{'weight': 'heavy'},
              },
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'theme typography lineHeight must be positive': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'theme',
            'props': <String, dynamic>{
              'typography': <String, dynamic>{
                'title': <String, dynamic>{'lineHeight': 0},
              },
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'theme typography color must be valid': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'theme',
            'props': <String, dynamic>{
              'typography': <String, dynamic>{
                'title': <String, dynamic>{'color': 'bad-token'},
              },
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'theme requires one child': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'theme',
            'props': <String, dynamic>{},
            'children': <Object?>[],
          };
        }),
        'missing paged item template': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'pagedBackendBuilder',
            'props': <String, dynamic>{
              'requestId': 'coupons',
              'endpoint': 'coupons/page',
            },
            'children': <Object?>[],
          };
        }),
        'empty form': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'form',
            'props': <String, dynamic>{'id': 'application'},
            'children': <Object?>[],
          };
        }),
        'invalid form field name': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'form',
            'props': <String, dynamic>{'id': 'application'},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'textInput',
                'props': <String, dynamic>{
                  'name': 'FullName',
                  'label': 'Full name',
                },
                'children': <Object?>[],
              },
            ],
          };
        }),
        'dropdown initial value mismatch': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'dropdown',
            'props': <String, dynamic>{
              'name': 'program',
              'label': 'Program',
              'initialValue': 'missing',
              'options': <Object?>[
                <String, dynamic>{'value': 'stem', 'label': 'STEM'},
              ],
            },
            'children': <Object?>[],
          };
        }),
        'invalid widget color': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'icon',
            'props': <String, dynamic>{'name': 'settings', 'color': 'red'},
            'children': <Object?>[],
          };
        }),
        'unknown widget icon': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'icon',
            'props': <String, dynamic>{'name': 'video'},
            'children': <Object?>[],
          };
        }),
        'invalid widget tone': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'badge',
            'props': <String, dynamic>{'label': 'New', 'tone': 'brand'},
            'children': <Object?>[],
          };
        }),
        'negative widget spacing': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'padding',
            'props': <String, dynamic>{
              'padding': <String, dynamic>{'left': -1},
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'missing widget child': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'container',
            'props': <String, dynamic>{},
            'children': <Object?>[],
          };
        }),
        'invalid avatar source count': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'avatar',
            'props': <String, dynamic>{'initials': 'MH', 'icon': 'person'},
            'children': <Object?>[],
          };
        }),
        'invalid avatar image url': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'avatar',
            'props': <String, dynamic>{'imageUrl': 'http://example.com/a.png'},
            'children': <Object?>[],
          };
        }),
        'invalid grid columns': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'grid',
            'props': <String, dynamic>{'columns': 0},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'empty wrap': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'wrap',
            'props': <String, dynamic>{},
            'children': <Object?>[],
          };
        }),
        'invalid progress range': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'progress',
            'props': <String, dynamic>{'value': 2, 'max': 1},
            'children': <Object?>[],
          };
        }),
        'emptyState action missing label': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'emptyState',
            'props': <String, dynamic>{
              'title': 'Empty',
              'action': <String, dynamic>{
                'type': 'state.set',
                'props': <String, dynamic>{'key': 'empty.retry', 'value': true},
              },
            },
            'children': <Object?>[],
          };
        }),
        'section label missing action': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'section',
            'props': <String, dynamic>{
              'title': 'Featured',
              'actionLabel': 'View all',
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Body'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'invalid align value': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'align',
            'props': <String, dynamic>{'alignment': 'middle'},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'invalid spacer flex': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'spacer',
            'props': <String, dynamic>{'flex': 0},
            'children': <Object?>[],
          };
        }),
        'empty listView': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'listView',
            'props': <String, dynamic>{},
            'children': <Object?>[],
          };
        }),
        'negative listView padding': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'listView',
            'props': <String, dynamic>{
              'padding': <String, dynamic>{'top': -1},
            },
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'invalid safeArea flag': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'safeArea',
            'props': <String, dynamic>{'left': 'yes'},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'invalid visibility flag': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'visibility',
            'props': <String, dynamic>{'visible': 'yes'},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'invalid opacity value': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'opacity',
            'props': <String, dynamic>{'opacity': 2},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'missing aspectRatio value': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'aspectRatio',
            'props': <String, dynamic>{},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'invalid aspectRatio value': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'aspectRatio',
            'props': <String, dynamic>{'aspectRatio': 0},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'empty stack': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'stack',
            'props': <String, dynamic>{},
            'children': <Object?>[],
          };
        }),
        'invalid stack alignment': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'stack',
            'props': <String, dynamic>{'alignment': 'middle'},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'invalid stack clip flag': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'stack',
            'props': <String, dynamic>{'clip': 'no'},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'positioned without constraints': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'positioned',
            'props': <String, dynamic>{},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'invalid positioned value': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'positioned',
            'props': <String, dynamic>{'top': -1},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'invalid positioned horizontal combo': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'positioned',
            'props': <String, dynamic>{'left': 1, 'right': 1, 'width': 10},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'invalid expanded flex': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'expanded',
            'props': <String, dynamic>{'flex': 0},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'expanded missing child': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'expanded',
            'props': <String, dynamic>{'flex': 1},
            'children': <Object?>[],
          };
        }),
        'flexible extra children': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'flexible',
            'props': <String, dynamic>{'fit': 'loose', 'flex': 1},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'One'},
                'children': <Object?>[],
              },
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Two'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'invalid flexible fit': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'flexible',
            'props': <String, dynamic>{'fit': 'fill', 'flex': 1},
            'children': <Object?>[
              <String, dynamic>{
                'type': 'text',
                'props': <String, dynamic>{'data': 'Hi'},
                'children': <Object?>[],
              },
            ],
          };
        }),
        'invalid ui action': _screenWith((json) {
          json['root'] = <String, dynamic>{
            'type': 'primaryButton',
            'props': <String, dynamic>{
              'label': 'Save',
              'action': <String, dynamic>{
                'type': 'ui.toast',
                'props': <String, dynamic>{'message': ''},
              },
            },
            'children': <Object?>[],
          };
        }),
        'invalid cache key': _cacheActionScreen('cache.set', <String, dynamic>{
          'key': '../products',
          'value': true,
        }),
        'invalid cache bucket': _cacheActionScreen(
          'cache.get',
          <String, dynamic>{'key': 'products', 'bucket': 'session'},
        ),
        'invalid cache priority': _cacheActionScreen(
          'cache.set',
          <String, dynamic>{
            'key': 'products',
            'value': true,
            'priority': 'hostPinned',
          },
        ),
        'invalid cache ttl': _cacheActionScreen('cache.set', <String, dynamic>{
          'key': 'products',
          'value': true,
          'ttlMs': 0,
        }),
        'invalid cache skipMissing': _cacheActionScreen(
          'cache.get',
          <String, dynamic>{'key': 'products', 'skipMissing': 'yes'},
        ),
        'invalid cache target state': _cacheActionScreen(
          'cache.get',
          <String, dynamic>{'key': 'products', 'targetState': 'auth.token'},
        ),
        'invalid cache value': _cacheActionScreen(
          'cache.set',
          <String, dynamic>{
            'key': 'products',
            'value': <String, Object?>{'': true},
          },
        ),
        'invalid cache non-finite value': _cacheActionScreen(
          'cache.set',
          <String, dynamic>{'key': 'products', 'value': double.infinity},
        ),
        'invalid cache unknown prop': _cacheActionScreen(
          'cache.clear',
          <String, dynamic>{'all': true},
        ),
      };

      for (final entry in cases.entries) {
        expect(
          () => const MpScreenValidator().validate(
            entry.value,
            expectedScreenId: 'coupon_home',
          ),
          throwsA(isA<MiniProgramRenderException>()),
          reason: entry.key,
        );
      }
    });
  });
}

Map<String, dynamic> _textNode(String data) {
  return <String, dynamic>{
    'type': 'text',
    'props': <String, dynamic>{'data': data},
    'children': <Object?>[],
  };
}

Map<String, dynamic> _backendLoadMoreActionJson() {
  return <String, dynamic>{
    'type': 'backend.loadMore',
    'props': <String, dynamic>{
      'requestId': 'products',
      'endpoint': '/products',
    },
  };
}
