name: mini_program_tooling
description: Local developer and CI tooling for the Flutter mini-program platform.
version: 0.3.9
repository: https://github.com/mehedi8603651/flutter-mini-program-platform

executables:
  miniprogram: miniprogram

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0
  crypto: ^3.0.6
  http: ^1.5.0
  mini_program_contracts: ^0.1.1
  path: ^1.9.1
  pub_semver: ^2.2.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
