name: mini_program_sdk
description: Portable runtime SDK for the Flutter mini-program platform.
version: 0.1.3
repository: https://github.com/mehedi8603651/flutter-mini-program-platform

environment:
  sdk: ^3.10.0
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  json_annotation: ^4.11.0
  mini_program_contracts: ^0.1.0
  path: ^1.9.1
  stac: ^1.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
